spinnaker/echo

echo-web/echo-web.gradle

@ewiseblatt @dstengle FYI
This generates a legit start script for the deb file without interfering with the bootRun task

inject the packaging specific spring config location via startScripts extension

---

echo-rest/src/main/groovy/com/netflix/spinnaker/echo/config/RestConfig.groovy
echo-rest/src/main/groovy/com/netflix/spinnaker/echo/config/RestProperties.groovy
echo-rest/src/main/groovy/com/netflix/spinnaker/echo/config/RestUrls.groovy
echo-rest/src/main/groovy/com/netflix/spinnaker/echo/events/RestEventListener.groovy
echo-rest/src/test/groovy/com/netflix/spinnaker/echo/events/RestEventListenerSpec.groovy

allow configuration of multiple rest endpoints to send events to

---

echo-core/src/main/groovy/com/netflix/spinnaker/echo/events/EventPropagator.groovy

Fixes spinnaker/spinnaker#696
@tomaslin PTAL

use observeOn instead of subscribeOn for event dispatch

---

echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/BuildEvent.groovy
echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/Event.groovy
echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/BuildEventMonitor.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/BuildEventMonitorSpec.groovy
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineConfigsPollingAgentSpec.groovy
echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineTriggerActionConverterSpec.groovy
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy

add the ability to trigger off a pipeline based on a git trigger from stash

stash trigger

---

echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/trigger/BuildEvent.groovy
echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/trigger/DockerEvent.groovy
echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/trigger/GitEvent.groovy
echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/trigger/TriggerEvent.groovy
echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/BuildEventMonitor.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/DockerEventMonitor.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/TriggerMonitor.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/DockerEventMonitorSpec.groovy
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineConfigsPollingAgentSpec.groovy
echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineTriggerActionConverterSpec.groovy

Needs https://github.com/spinnaker/igor/pull/65
With this change, and a custom pipeline sent to front50, I was able to trigger a pipeline off a push to github registered to a docker repository on dockerhub.

provider/docker: Trigger listener

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/DockerEventMonitor.java

provider/docker: Digests are optional

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/DockerEventMonitor.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/DockerEventMonitorSpec.groovy
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy

Add ability to handle regex in docker trigger.

Add regex to docker image

---

echo-core/src/main/groovy/com/netflix/spinnaker/echo/services/Front50Service.groovy

Front50 service cleanup

---

echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/PipelineConfigsPollingAgent.groovy
echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineConfigsPollingAgentSpec.groovy

@ajordens @duftler @tomaslin PTAL

consider pipeline disabled status when modifying triggers

---

build.gradle
echo-web/echo-web.gradle

@ttomsu 
spinnaker introduced at 0.63.0.

Added stackdriver and updated to dependencies 0.63.0

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiatorSpec.groovy

@jtk54 @cfieber @ajordens @duftler PTAL
tag: https://github.com/spinnaker/fiat/issues/36

Conditionally include the 'runAsUser' iff Fiat is enabled

---

echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy

Fixing SpEL condition on compensation job

---

build.gradle
echo-web/echo-web.gradle

update to latest build, switch ospackaging to project conventions

---

build.gradle

Update spinnaker-dependencies for monitoring support.

---

halconfig/echo.yml

Base echo halconfig

---

echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/PipelineTriggerConverter.groovy
echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineTriggerActionConverterSpec.groovy

Adds runAsUser to CRON triggers

---

halconfig/echo.yml

Update halconfig timezone to pull from global settings

---

echo-web/config/echo.yml

Added default orca endpoint.

---

Dockerfile
Dockerfile.slim
build.gradle
cloudbuild.yaml

Slim build & gradle project bump

---

build.gradle

chore(gradle) spinnaker-gradle-project version bump.

---

echo-core/src/main/groovy/com/netflix/spinnaker/echo/services/Front50Service.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.groovy

Depends on https://github.com/spinnaker/orca/pull/1171
@tomaslin PTAL

Assume notification preferences are set upstream

---

echo-web/src/main/groovy/com/netflix/spinnaker/echo/config/ComponentConfig.groovy

Adds basic controller.invocations spectator metrics collector

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/BuildEventMonitor.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/BuildEventMonitorSpec.groovy
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy

Support a new trigger type called `travis`

feat(travis stage) Support new `travis` triggerType

---

echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
echo-model/src/test/groovy/com/netflix/spinnaker/echo/model/PipelineSpec.groovy

@robzienert this makes the templated pipelines work even if they are triggered automatically

feat(pipelinetemplate) Add config and type attributes to the trigger payload

---

build.gradle
echo-core/echo-core.gradle
echo-core/src/main/groovy/com/netflix/spinnaker/echo/events/EventPropagator.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/EmailNotificationAgent.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/HipchatNotificationAgent.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgent.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/pagerduty/PagerDutyNotificationService.groovy
echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy
echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/PipelineConfigsPollingAgent.groovy
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy

Kicking around the idea of more structured logs for our services so things may be easier to index in search. This converts the entirety of echo (from what I saw as worthwhile) as a POC before biting off bigger services.
Uses https://github.com/logstash/logstash-logback-encoder
@spinnaker/reviewers WDYT? If it's interesting, I'll update spinnaker-dependencies.

refactor(logs): Structured logs

---

build.gradle
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/VelocityConfig.groovy
echo-web/config/echo.yml
echo-web/src/main/groovy/com/netflix/spinnaker/echo/Application.groovy
echo-web/src/main/resources/application.properties

Merging into `boot-upgrade` branch

chore(springBoot): Upgrade to Spring Boot 1.5.4

---

echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/trigger/PubsubEvent.java
echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
echo-model/src/main/java/com/netflix/spinnaker/echo/model/pubsub/MessageDescription.java
echo-model/src/main/java/com/netflix/spinnaker/echo/model/pubsub/PubsubType.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitor.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/PubsubEventMonitorSpec.groovy
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/config/google/GooglePubsubConfig.java
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/config/google/GooglePubsubProperties.java
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandler.java
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubSubscribers.java
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubMonitor.java
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubSubscriber.java
echo-pubsub/src/test/groovy/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandlerSpec.groovy
echo-pubsub/src/test/groovy/com/netflix/spinnaker/echo/pubsub/redis/EmbeddedRedisConfiguration.groovy
echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineConfigsPollingAgentSpec.groovy
echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineTriggerActionConverterSpec.groovy

Adds specs for a crucial classes in this code path. Also refactors the 10+ arg `Trigger` constructors into `builder`s.

feat(pubsub): Process message events and forward matching triggers.

---

build.gradle
echo-model/echo-model.gradle
echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
echo-model/src/main/java/com/netflix/spinnaker/echo/model/pubsub/MessageDescription.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitor.java
echo-pubsub/echo-pubsub.gradle
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/config/google/GooglePubsubConfig.java
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/config/google/GooglePubsubProperties.java
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubSubscriber.java
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/utils/MessageArtifactTranslator.java
echo-pubsub/src/test/groovy/com/netflix/spinnaker/echo/pubsub/utils/MessageArtifactTranslatorSpec.groovy

Adds proper artifact model parsing from pub/sub messages and propagates artifacts to Orca. The spec gives an idea what jinja is capable of, but we'll have to document some of the cookie-cutter use cases.

feat(pubsub): Parse artifacts from pub/sub message contents.

---

echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/EmailNotificationAgent.groovy

Minor regression that prevents stages with comments from sending email notifications.

fix(email): include markdown converter in email notification agent call

---

echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
echo-model/src/main/java/com/netflix/spinnaker/echo/model/pubsub/MessageDescription.java
echo-model/src/main/java/com/netflix/spinnaker/echo/model/pubsub/PubsubSystem.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitor.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/PubsubEventMonitorSpec.groovy
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandler.java
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubSubscribers.java
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubMonitor.java
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubSubscriber.java
echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/model/PubsubSubscriber.java
echo-pubsub/src/test/groovy/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandlerSpec.groovy

The frontend (correctly) expects `pubsubSystem` instead of `pubsubType`.

fix(pubsub): s/pubsubType/pubsubSystem/

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiatorSpec.groovy

fix(pipelinetriggers): Add retry on network & http errors

---

build.gradle

Needed to automatically pick up new 'match' logic for artifacts.

chore(kork): Bump spin-deps to upgrade kork

---

echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/pagerduty/PagerDutyNotificationService.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/pagerduty/PagerDutyService.groovy

Related orca PR: https://github.com/spinnaker/orca/pull/1797

feat(pagerduty): Support details field and add error handling/reporting

---

echo-web/lib/systemd/system/echo.service

Add systemd service config for echo.

feat(local_debian): Add echo systemd service config.

---

echo-web/lib/systemd/system/echo.service

Add systemd service configuration for echo.

Xenial build

---

echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitor.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitor.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/PubsubEventMonitorSpec.groovy
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy

Also fixes mismatch in trigger field/value in webhook monitor.

fix(pubsub): Add payload to pubsub triggers.

---

echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitorSpec.groovy

* Fix a test description by removing unused `#triggerType`
* Remove a test that is redundant

fix(tests): Small fixes to PubsubEventMonitorSpec

---

echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/trigger/WebhookEvent.groovy
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitor.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy

1. NPE against pipelines with empty trigger definitions
2. Failed to inject artifacts into pipeline
3. Failed to set correct (untransformed) payload

fix(webhooks): assorted triggering problems

---

echo-pubsub/echo-pubsub.gradle

chore: bump pubsub client library

---

halconfig/echo.yml

chore(halconfig): add redis config

---

echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/NotificationTemplateEngine.groovy
echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/NotificationTemplateEngineSpec.groovy

- handles subject/body processing when templateGroup is nil
- allows controlling formatting of subject/body

feat(notifications): Allow processing when template group is not passed in request

---

echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/amazon/SQSSubscriberProvider.java

fix(sqs): fix startup

---

echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/amazon/SQSSubscriberProvider.java

@lwander this should be a better fix for https://github.com/spinnaker/echo/pull/235. Sorry about that!

fix(sqs): worker startup conditional on enabled

---

echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/EmailNotificationAgent.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/HipchatNotificationAgent.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgent.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/TwilioNotificationAgent.groovy
echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/EmailNotificationAgentSpec.groovy
echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgentSpec.groovy

fix(stage notifications): consuming updated orca payload (#238)

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/GitEventMonitor.java

`e = com.netflix.spinnaker.echo.model.Event@5d690d64`

fix(logging): Remove unnecessary log output

---

echo-notifications/src/main/resources/templates/swabbie/body.ftl
echo-notifications/src/main/resources/templates/swabbie/subject.ftl

- added a template for email body & subject for swabbie

feat(notifications): Adding an initial swabbie template for email

---

echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy

Fixing the gauge to accumulate all cron triggers.

fix(scheduler): Moving metrics to top-level

---

echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/JiraConfig.java
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/controller/EchoResponse.java
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/controller/NotificationController.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/email/EmailNotificationService.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/hipchat/HipchatNotificationService.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/jira/JiraNotificationService.java
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/jira/JiraProperties.java
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/jira/JiraService.java
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/NotificationService.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/pagerduty/PagerDutyNotificationService.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackNotificationService.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/twilio/TwilioNotificationService.groovy

- supports creating a jira issue
- ok client configurable to support x509 for auth

feat(jira): Adding Jira notification type

---

echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/jira/JiraNotificationService.java

Fixes https://github.com/spinnaker/spinnaker/issues/2734.

fix(jira): Allow echo to start up with jira disabled.

---

echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy

fix(webhooks): make copy of payload to avoid editing it

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/PipelineTriggerConfiguration.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/OrcaService.java
echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy
echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/MissedPipelineTriggerCompensationJobSpec.groovy

Ha-ha. Can't compensate hundreds of jobs at a time.

fix(cron): Partition pipeline config ids in compensation job

---

echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/bearychat/BearychatNotificationService.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/bearychat/BearychatService.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/bearychat/BearychatUserInfo.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/bearychat/CreateP2PChannelPara.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/bearychat/CreateP2PChannelResponse.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/bearychat/SendMessagePara.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/BearychatConfig.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/BearychatNotificationAgent.groovy
echo-notifications/src/main/resources/templates/manualJudgment/body-bearychat.ftl
echo-notifications/src/main/resources/templates/manualJudgmentContinue/body-bearychat.ftl
echo-notifications/src/main/resources/templates/manualJudgmentStop/body-bearychat.ftl

Add bearychat support.
This PR is related to [spinnaker/spinnaker#2874](https://github.com/spinnaker/spinnaker/issues/2874)

feat(notification): add bearychat support

---

echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubSubscriber.java

fix(pubsub/google): don't restart when subscription doesn't exist

---

echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubSubscriber.java

fix(pubsub/google): don't restart when subscription doesn't exist (#276)

---

build.gradle

Allow us to record request payload size; needed for Q3 work... would like a couple weeks' data so we can hit the ground running with a decent idea of usage.

chore(*): Bump spinnaker-dependencies to 0.158.0

---

echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/Event.groovy
echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/trigger/GitEvent.groovy
echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/trigger/TriggerEvent.groovy
echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/BuildEventMonitor.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/DockerEventMonitor.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/GitEventMonitor.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitor.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitor.java
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy
echo-webhooks/src/test/groovy/com/netflix/spinnaker/echo/controllers/WebhooksControllerSpec.groovy

Also related:
https://github.com/spinnaker/orca/pull/2292
https://github.com/spinnaker/gate/pull/560

feat(webhooks): Update webhooks endpoint to forward and return a eventId.

---

build.gradle
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/api/Notification.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/GoogleChatConfig.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/controller/NotificationController.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/googlechat/GoogleChatClient.java
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/googlechat/GoogleChatMessage.java
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/googlechat/GoogleChatNotificationService.java
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/googlechat/GoogleChatService.java
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/GoogleChatNotificationAgent.groovy
echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/GoogleChatNotificationAgentSpec.groovy
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/health/MonitoredPollerHealth.java

Add a new notification type Google Chat.
This is part of the issue spinnaker/spinnaker#2936

feat(notification): Add support for Google Chat.

---

echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/GoogleChatNotificationAgent.groovy

Fix a last minute bug introduced in previous PR. #282

fix(notifications): Fix variable reference bug in Google Chat

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCacheSpec.groovy

This fixes the /health endpoint and pipeline poller.

fix(healthcheck): pipelines might have no triggers

---

echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/artifacts/QuayArtifactExtractor.java

adds native quay artifact parser
fixes spinnaker/spinnaker#2322

feat(artifacts/quay): add native quay parser

---

echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java

Not an ideal way to expose a trigger field for custom triggers, but I need to stop overloading "expectedArtifactIds"

feat(echo): add trigger field for custom triggers that deal with artifacts

---

echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy

Fixing the bug and also dre's comment from other PR.

fix(cron): Adding fuzzy expression parsing support

---

echo-notifications/src/main/resources/templates/swabbie/body.ftl
echo-notifications/src/main/resources/templates/swabbie/subject.ftl

- back to original email format because html email is hard
- simplify email content
- each resource detail per row

chore(swabbie): formatting swabbie email notification

---

echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy
echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/MissedPipelineTriggerCompensationJobSpec.groovy

`dateContext.now` used to be initialized once when the service started and
was never updated, so `MissedPipelineTriggerCompensationJob` would keep
retriggering the same pipelines in the same time window over and over again.
Moving to a dynamic `dateContext.now()` should be enough to make the time
window an actually sliding window.

fix(cron): don't use a static time value in the cron compensation job

---

echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineTriggerAction.groovy

Reverting this change which broke cron triggering.

revert(cron): add cron pipeline started metric (#326)

---

echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy
echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/MissedPipelineTriggerCompensationJobSpec.groovy

Otherwise the pipelines triggered by the compensation seem to have a
manual/[anonymous] trigger

fix(cron): add explicit trigger in compensation job

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/BuildEventMonitor.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/DockerEventMonitor.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/GitEventMonitor.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitor.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/TriggerMonitor.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitor.java

There is a lot of duplicated code in the subclasses of TriggerMonitor; specifically a number of member variables are defined on all subclasses and can be pushed to the base class. Similarly, the core logic in
processEvent is the same for all subclasses and should live in the base class.

refactor(core): Push shared functionality to TriggerMonitor.java

---

echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java

This change does not change anything functionally, but adds some structure to the long list of fields in Trigger.java so it's easier to understand what each field is used for.

style(core): Add comments and re-order fields in Trigger.java

---

echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/OrcaService.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiatorSpec.groovy

Depends on https://github.com/spinnaker/orca/pull/2480.

fix(MPT): Fix templated pipeline triggers.

---

build.gradle
echo-web/echo-web.gradle
gradle/buildViaTravis.sh
gradle/init-publish.gradle
gradle/installViaTravis.sh
gradle/wrapper/gradle-wrapper.properties

Removes the spring boot plugin.
Ref: https://github.com/spinnaker/spinnaker/issues/2844

chore(builds): Introduces composite builds via gradle plugin.

---

build.gradle
echo-web/echo-web.gradle

Spring bootRun plugin used to do some magic to inherit this dependency.

fix(builds): Add spring data rest dependency to fix build.

---

Dockerfile

fix(build): Fixed Dockerfile for composite builds.

---

echo-notifications/src/main/resources/templates/swabbie/body.ftl
echo-notifications/src/main/resources/templates/swabbie/subject.ftl

@emjburns lets test this out on your machine today! I need help with:
- referencing the logo (static asset path?)
- referencing the index in the loop (this resource shows #foreach as deprecated so just wanted to check w/you on it: https://freemarker.apache.org/docs/ref_builtins_loop_var.html)
- adding the count to the subject line (was not sure if notification object is available to reference in that file)
Thanks!

feat(swabbie): adds notification email design

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/PipelineTriggerConfiguration.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java

config(front50): make the polling frequency a configurable property

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java

Port of https://github.com/spinnaker/echo/pull/397 to master.

fix(triggers): Fix triggered pipeline template artifact resolution.

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java

Reverts spinnaker/echo#398
@jervi FYI
Reverting this in favor of https://github.com/spinnaker/orca/pull/2510 which is a more simple approach for the time being.

Revert "fix(triggers): Fix triggered pipeline template artifact resolution."

---

echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
echo-model/src/test/groovy/com/netflix/spinnaker/echo/model/TriggerSpec.groovy
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java

This is a manual cherry-pick of https://github.com/spinnaker/echo/pull/418 into 1.10.  (The first commit applied cleanly, but the second I had to manually do.)
This bug only shows up behind a flag in 1.10, but I'd like to fix the behavior so people can test the flag.

 fix(MPT): Fix manual triggering of templated pipelines

---

echo-notifications/src/main/resources/templates/swabbie/body.ftl

For some reason that value can be null. Fixing this template to handle that.

fix(swabbie): fix email template to handle missing value

---

echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy
echo-webhooks/src/test/groovy/com/netflix/spinnaker/echo/controllers/WebhooksControllerSpec.groovy

Replace refs/heads/ same as for other types.

fix(webhooks/bitbucket): Refs for Bitbucket Server

---

echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/BitbucketWehbookEventHandler.java
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/GitWebhookHandler.java
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/GithubWebhookEventHandler.java
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/GitlabWehbookEventHandler.java
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/ScmWebhookHandler.java
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/StashWebhookEventHandler.java
echo-webhooks/src/test/groovy/com/netflix/spinnaker/echo/controllers/WebhooksControllerSpec.groovy

refactors git webhook handling by extracting the large if/else block
into individual handler classes.

refactor(webhooks): refactor git webhook handling

---

echo-artifacts/src/main/java/com/netflix/spinnaker/echo/config/KeelConfig.java

Fix for echo not starting if you don't have keel.

fix(artifacts): don't require keel

---

echo-web/echo-web.gradle
echo-web/src/test/java/com/netflix/spinnaker/echo/ApplicationSpec.java
echo-web/src/test/resources/echo-test.yml

Test that echo starts up with a very basic config, with just the baseUrl for each dependent service defined, and with beans mocking these services.

test(core): Basic startup test

---

build.gradle
echo-artifacts/src/main/java/com/netflix/spinnaker/echo/config/KeelConfig.java
echo-model/echo-model.gradle
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/GithubConfig.java
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/HipchatConfig.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/PagerDutyConfig.java
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/SlackConfig.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/TwilioConfig.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/GithubNotificationAgent.java
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/NotificationTemplateEngine.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgent.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/pagerduty/PagerDutyNotificationService.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackNotificationService.groovy
echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/ManualJudgmentTemplateTest.groovy
echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/NotificationServiceSpec.groovy
echo-pipelinetriggers/echo-pipelinetriggers.gradle
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/IgorConfig.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/PipelineTriggerConfiguration.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
echo-rest/src/main/groovy/com/netflix/spinnaker/echo/config/RestConfig.groovy
echo-rest/src/main/groovy/com/netflix/spinnaker/echo/events/RestEventListener.groovy
echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/config/SchedulerConfiguration.groovy
echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/MissedPipelineTriggerCompensationJob.groovy
echo-web/echo-web.gradle
echo-web/src/main/java/com/netflix/spinnaker/echo/Application.java
echo-web/src/main/java/com/netflix/spinnaker/echo/config/Front50Config.java
echo-web/src/test/java/com/netflix/spinnaker/echo/ApplicationSpec.java

Echo to Boot2

---

echo-core/src/main/java/com/netflix/spinnaker/echo/build/BuildInfoService.java

This is necessary to allow expected artifacts to match against artifacts surfaced under the trigger `buildInfo` property, which is where artifacts appear for CI builds like Jenkins.
Pairs with https://github.com/spinnaker/igor/pull/401 to add support for expected artifact matchable Jenkins artifacts.

feat(artifacts): Support inflation of artifacts from trigger buildInfo

---

echo-core/src/main/java/com/netflix/spinnaker/echo/services/Front50Service.java
echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/OrcaService.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCacheSpec.groovy

Echo has its own cache of pipeline configs, but does not hydrate templated pipeline configs into the full runnable pipeline. Hence if you define a trigger in the template, Echo will not trigger it when it receives a matching trigger event.

fix(MPT): Fixes triggering for template triggers.

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/IgorConfig.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BuildEventHandler.java

Depends on https://github.com/spinnaker/igor/pull/374, please see that PR for a description.

feat(buildmasters): Permission support for build masters (CI's)

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java

If planning a pipeline fails, make sure to log a metric

fix(triggers): Better error handling for trigger failures

---

echo-web/echo-web.gradle

Prereq for spinnaker/kork#273 merge

chore(dependencies): ensure direct dependency on kork-secrets-aws

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java

If the pipeline planning in Orca fails because of an error in the template, the error is just logged in Echo and the execution disappears. This makes it very hard to debug failing templates. I don't know if this happens to MPT v2 as well, but it is a problem for v1 at least.
This fix will let the pipeline triggering continue even if the planning fails, so that Orca later can register the failed execution.

fix(pipelines): Don't swallow exceptions when parsing pipeline templates

---

echo-webhooks/echo-webhooks.gradle
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/artifacts/ArtifactExtractor.java
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/artifacts/NexusArtifactExtractor.java
echo-webhooks/src/test/java/com/netflix/spinnaker/echo/artifacts/NexusArtifactExtractorTest.java

Nexus3 contains a `Webhook: Repository` capability that this extractor builds artifacts for:

feat(triggers): Add Nexus webhook artifact extractor

---

build.gradle
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/OrcaService.java
gradle.properties
gradle/wrapper/gradle-wrapper.properties

updates kork to 5.3.4
updates spinnaker-gradle-project to 6.5.0
updates fiat to 1.0.4

chore(dependencies): externalize versions to properties

---

echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/BitbucketWehbookEventHandler.java

Fixes the determination for bitbucket server or cloud webhooks, cleans up some erroneous code and fixes a typo.

fix(webhooks): bitbucket server or cloud determination

---

echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/BitbucketWehbookEventHandler.java

(Backported fix from master) Fixes the determination for bitbucket server or cloud webhooks, cleans up some erroneous code and fixes a typo

fix(webhooks): bitbucket server or cloud determination (#572)

---

echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/BitbucketWehbookEventHandler.java

Small typo on the bitbucket server webhook handler.

fix(bitbucket): typo on eventType switch

---

echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
echo-model/src/test/groovy/com/netflix/spinnaker/echo/model/PipelineSpec.groovy
gradle.properties

jackson bump to 2.9.9 exposed a flaw in pipeline model having two `config` setters
add explicit getter/setter method

fix(kork_update): bump kork to 5.8 and fix pipeline model

---

echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineTriggerJob.groovy

this will aid debugging multiple triggers, if any.
Or, confirm that all works as expected

fix(cron): add trigger id to pipeline execution logs

---

echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/googlechat/GoogleChatMessage.java

Fixes https://github.com/spinnaker/spinnaker/issues/4754.

fix(notifications/googlechat): Fix field visibility.

---

echo-artifacts/src/main/java/com/netflix/spinnaker/echo/artifacts/ArtifactEmitter.java

A log message like this in `keel` has proven very useful. Moving that message to echo.

chore(artifact): logging the artifacts we get

---

echo-notifications/src/main/resources/templates/swabbie/body.ftl
echo-notifications/src/main/resources/templates/swabbie/subject.ftl

- Updated template to reflect new model
- based off of https://github.com/spinnaker/echo/pull/665

fix(swabbie): Update swabbie email template

---

echo-notifications/src/main/resources/templates/swabbie/body.ftl

fix(swabbie) fixing typo in email template

---

.mergify.yml

this makes it easier to see/audit all automatically merged PRs

chore(mergify): make mergify add a label when a PR is automatically merged

---

README.md

also tests mergify add label behavior

chore(readme): add mergify status

---

echo-notifications/src/main/resources/templates/swabbie/body.ftl

- use deletionDate passed by swabbie

fix(swabbie): Update email template

---

echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/TelemetryEventListener.java
echo-telemetry/src/test/groovy/com/netflix/spinnaker/echo/telemetry/TelemetryEventListenerSpec.groovy
gradle.properties

feat(stats): Update stat collection to whitelisted cloud providers

---

echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandler.java
echo-pubsub-core/src/test/groovy/com/netflix/spinnaker/echo/pubsub/redis/EmbeddedRedisConfiguration.groovy
gradle.properties

See https://github.com/spinnaker/spinnaker/issues/5134
Dependent on https://github.com/spinnaker/kork/pull/419 for a Spring Boot dependency upgrade

chore(dependencies): Upgrade Spring Boot to 2.2.1

---

echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandler.java
echo-pubsub-core/src/test/groovy/com/netflix/spinnaker/echo/pubsub/redis/EmbeddedRedisConfiguration.groovy
gradle.properties

Revert "chore(dependencies): Upgrade Spring Boot to 2.2.1 (#702)"
This reverts commit a8d0c895

chore(dependencies): Reverting Spring Boot 2.2 upgrade

---

echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/SlackLegacyProperties.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackClient.groovy
echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackService.groovy
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java

For backward compatibility, this is driven by a config that's off by default

feat(slack): Add ability for slack to expand user names

---

echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/utils/NodeIdentity.java

Fixes https://github.com/spinnaker/spinnaker/issues/5453
.. I _think_.

fix(pubsub): Default NodeIdentity to 'UnknownHost' to prevent NPE

---

echo-notifications/src/main/resources/templates/swabbie/subject.ftl

Update cleanup email subject line

fix(swabbie): Update cleanup email subject line

---

echo-telemetry/echo-telemetry.gradle

In an upcoming kork bump, some things that were api dependencies will be moved to implementation; add these explicitly where they are used.

refactor(core): Clean up dependencies

---

echo-api/src/main/java/com/netflix/spinnaker/echo/api/events/Metadata.java

Same as https://github.com/spinnaker/echo/pull/863 but without the tests so as not to pull in the Kotlin dependency (which makes cherry picking the change complicated).

fix(headers): Metadata requestHeaders lookup should be case insensitive

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiatorSpec.groovy

Allow `PipelineInitiator` to read the `orca.enabled` property from dynamic config so it can be changed at runtime

fix(config): Allow dynamic config in pipeline initiator

---

echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriberProvider.java

This will allow us to migrate off Dynomite without much of a todo: We can set `pubsub.amazon.enabled=false` scoped only to `currentServerGroup` just before deploying the new version. This will cause the existing server group to stop processing pubsub messages, while the new server group running against Elasticache will be `enabled` and start picking up messages where the prior server group left off.
I don't believe we'd have much (if any) duplicated triggers this way, only a small processing delay which is fine.

feat(sqs): Support dynamically enabling pubsub subscriber

---

echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
echo-model/src/main/java/com/netflix/spinnaker/echo/model/trigger/PluginEvent.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/PluginEventHandler.java

This is a breaking change. Depends on https://github.com/spinnaker/igor/pull/757

feat(plugins): Expose additional plugin release info

---

echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/InteractiveNotificationCallbackHandler.groovy

We dynamically build retrofit services to relay interactive notification callbacks to downstream services from `echo` because the target service is not known upfront. When `echo` was reconfigured to talk to `keel` via metatron, this particular code path fell through the cracks. This PR uses the new `OkHttpClientProvider` to build the retrofit service to fix that.

fix(notifications): Fix okhttp client configuration for notification callbacks

---

README.md

Update interface name to match the actual interface.

fix(docs): Updates interface name

---

echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
echo-model/src/main/java/com/netflix/spinnaker/echo/model/trigger/PluginEvent.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/PluginEventHandler.java

It will be useful to have this data on the plugin trigger.
Related to:
https://github.com/spinnaker/igor/pull/793
https://github.com/spinnaker/orca/pull/3756

feat(plugins): Add description and provider to PluginEvent

---

echo-telemetry/src/test/kotlin/com/netflix/spinnaker/echo/telemetry/InstanceIdSupplierTest.kt

We should make sure that we close the redis we create so that we don't leave processes running after the test exits.

fix(test): Fix redis leak in test

---

echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BaseTriggerEventHandler.java
echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/PluginEventHandler.java
echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubMonitor.java
echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/SpinnakerInstanceDataProvider.kt
echo-telemetry/src/test/kotlin/com/netflix/spinnaker/echo/telemetry/ExecutionDataProviderTest.kt
echo-telemetry/src/test/kotlin/com/netflix/spinnaker/echo/telemetry/PipelineCountsDataProviderTest.kt
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/GitlabWehbookEventHandler.java
gradle.properties

This includes updates to google-java-format and ktlint, so requires some
formatting changes. These were made with a simple `./gradlew spotlessApply`.

chore(spotless): upgrade spinnaker gradle plugin

---

build.gradle
gradle.properties
gradle/kotlin.gradle

--Fixing kotlin version mismatches between Kork and Gate.

fix(misc): Upgraded kotlin version to match kork

---

echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/BitbucketWebhookEventHandler.java
echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/GitlabWebhookEventHandler.java
echo-webhooks/src/test/groovy/com/netflix/spinnaker/echo/controllers/WebhooksControllerSpec.groovy
echo-webhooks/src/test/java/com/netflix/spinnaker/echo/scm/BitbucketWebhookEventHandlerTest.java
echo-webhooks/src/test/resources/bitbucket_payload.json

prevent NPE when handling bitbucket payload

fix(bitbucket): prevent NPE when handling bitbucket payload

---

echo-bom/echo-bom.gradle
echo-pipelinetriggers/echo-pipelinetriggers.gradle
echo-web/echo-web.gradle
gradle.properties

chore(deps): update fiat to 1.27.0, use new maven coordinates

---

echo-notifications/src/main/resources/templates/manualJudgment/body-email.ftl
echo-notifications/src/main/resources/templates/manualJudgment/variables-email.ftl
echo-notifications/src/main/resources/templates/manualJudgmentContinue/body-email.ftl
echo-notifications/src/main/resources/templates/manualJudgmentStop/body-email.ftl
echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/ManualJudgmentTemplateTest.groovy

* Remove "for more details" footer and link to the Deck UI
* Add random bolding and italics
* Consistent with slack notification
* Fixes url escaping issue
Based on https://github.com/spinnaker/echo/pull/1086
Before (broken url):
After (valid link):

feat(manualJudgment): Change formatting of manual judgment emails
