- echo-web/config/echo.yml
Caused all notification services to send links pointing to:
``http://localhost:8083/#/applications/XXX/executions/U-U-I-D``
Where they should be:
``http://localhost:9000/#/applications/XXX/executions/U-U-I-D``
> Fixed spinnaker default port from 8083 to 9000.

- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/PipelineConfigsPollingAgent.groovy
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/PipelineTriggerConverter.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineConfigsPollingAgentSpec.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineTriggerActionConverterSpec.groovy
- Default to America/Los_Angeles.
- Respect timezone when determining if triggers and action instance are in sync.
> Externalize timezone for CRON evaluation as config property.

- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/config/CassandraConfig.groovy
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/config/SchedulerConfiguration.groovy
Make cassandra configuration conditional, but enabled by default for backwards compatibility.
> Add in-memory as an option

- echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/Event.groovy
- echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/trigger/WebhookEvent.groovy
- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
- echo-pipelinetriggers/echo-pipelinetriggers.gradle
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/DockerEventMonitor.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitor.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineConfigsPollingAgentSpec.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineTriggerActionConverterSpec.groovy
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy
Note: This is a new PR to replace #81 
Webhook support expects a JSON payload in the POST.
This JSON is a map of items. These items are compared
to a map of "constraints" in the Trigger configuration.
If all the constraints have matching items in the payload
map, the pipeline trigger fires.
Constraints that have a name and value must have an exact
match in the webhook payload.
Constraints that have a name but the value is an empty string
are considered met as long as there is an item in the payload
with the same name, regardless of the value of the item in the
payload JSON.
> PR for review: Adds support for starting a pipeline from a webhook POST.

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitor.java
The webhook trigger added in https://github.com/spinnaker/echo/pull/85 never verified that the trigger type was correct, but only that the incoming trigger type matched that of an arbitrary registered trigger. The result is that with this code, an incoming jenkins trigger would kick off every jenkins triggered pipeline once, and the correct jenkins triggered pipeline a second time. I'm guessing this wasn't caught since that code was never released.
@spinnaker/reviewers PTAL
> triggers: fix webhook bug

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/DockerEventMonitor.java
@duftler When a tag isn't specified, don't trigger on changes to "latest", since 1. specifying "latest" as the source tag is anti-pattern, and 2. this will cause duplicate builds when "latest" is a valid tag, and a change to separate tag was pushed (and expected).
> docker: Avoid duplicate triggers

- echo-core/src/main/groovy/com/netflix/spinnaker/echo/services/Front50Service.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/PagerDutyConfig.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/pagerduty/PagerDutyNotificationService.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/pagerduty/PagerDutyService.groovy
- New INCIDENT Notification Type ... PagerDuty is just one possible implementation (payload should be generic enough to support alternative incident response systems)
- PRs in `orca` and `deck` are forthcoming
> Pager Duty Support

- echo-web/src/main/groovy/com/netflix/spinnaker/echo/config/Front50Config.groovy
the spring config around retrofit is a horrible horrible mess in this app due to the way it has
frankensteined together all the previous services, but this config change should only be
necessary for the connections to front50 and orca where it will get picked up
@spinnaker/netflix-reviewers FYI
> add connectionPool configuration that seems to soothe the OkHttpClient

- echo-web/echo-web.gradle
This change will fix problems where logrotate ignores
/etc/logrotate.d/echo due to 'bad file mode.'
For Spinnaker issue [#904](https://github.com/spinnaker/spinnaker/issues/904)
> Update logrotate file permissions

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/TriggerMonitor.java
Working on the ability to disable pipelines...
Is this all we'd need to do to stop triggering if `disabled: true` is set on the pipeline config?
@tomaslin @cfieber @ajordens PTAL
> do not fire triggers if pipeline is disabled

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/OrcaService.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/MissedPipelineTriggerCompensationJobSpec.groovy
Enables performing deployments or restarts with the in-memory scheduler so that it will execute any missed cron executions. Can be configured as below.
```
scheduler:
enabled: true
compensationJob:
enabled: true
windowMs: 30000 # optional
```
The compensation job will ignore any missed executions that fall below the configured time window.
@spinnaker/netflix-reviewers @duftler PTAL
> Adding in-memory scheduler compensation job

- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy
Fixes NPE where pipeline triggers list object is null.
cc @ajordens
> Graceful handling of null triggers list

- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy
- echo-webhooks/src/test/groovy/com/netflix/spinnaker/echo/controllers/WebhooksControllerSpec.groovy
Github ships a ping request when you set up webhook, this results in an error using echo.
This PR addresses this issue.
https://developer.github.com/enterprise/2.8/webhooks/#ping-event
> Support the ping events from github webhooks

- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/BuildEventMonitorSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/GitEventMonitorSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy
PR [#153](https://github.com/spinnaker/igor/pull/153) has been opened against Igor.
PR's are being opened against Deck and Gate.
BitBucket Server (a.k.a. Stash) support already exists. This adds BitBucket Cloud support of pipeline triggers based on BitBucket webhooks and provides Orca the ability to retrieve a list of commits from BitBucket as part of it's GetCommits stage.
> Add BitBucket support

- echo-rest/src/main/groovy/com/netflix/spinnaker/echo/config/RestConfig.groovy
- echo-rest/src/main/groovy/com/netflix/spinnaker/echo/config/RestProperties.groovy
- echo-rest/src/test/groovy/com/netflix/spinnaker/echo/config/RestConfigSpec.groovy
This feature started because I needed to be able to set the Authorization header in order to send events to Splunk.
This PR will allow you to set headers in two ways.
1. Directly in `echo-local.yml`:
```yaml
rest:
enabled: true
endpoints:
- wrap: false
url: http://www.example.com
headers:
Authorization: Splunk MYSECRETKEYHERE
```
2. In a file that contains the headers you want to include:
```yaml
rest:
enabled: true
endpoints:
- wrap: false
url: http://www.example.com
headersFile: /mnt/mysecrets/splunkKey
```
where `/mnt/mysecrets/splunkKey` looks like:
```
Authorization: Splunk MYSECRETKEYHERE
```
In the examples above, I only used the `Authorization` header. However, you can specify any header you want. 
If there are conflicts with headers then the header in the `headersFile` will be …
> feat(core): Allow configurable headers for rest endpoints

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/BuildEventMonitor.java
travis trigger check switched the comparison on trigger.getType to not be null safe
> fix(triggers): fix NPE regression on BuildEventMonitor.

- echo-rest/src/main/groovy/com/netflix/spinnaker/echo/config/RestProperties.groovy
- echo-rest/src/main/groovy/com/netflix/spinnaker/echo/events/RestEventListener.groovy
- echo-rest/src/main/groovy/com/netflix/spinnaker/echo/events/RestEventTemplateEngine.groovy
- echo-rest/src/test/groovy/com/netflix/spinnaker/echo/events/RestEventListenerSpec.groovy
- echo-rest/src/test/groovy/com/netflix/spinnaker/echo/events/SimpleEventTemplateSpec.groovy
When configuring webhooks in Echo, it only supports two types of payloads:
```
{ "content":[..], "details":[..]}
```
or using the `wrap` property which forces the payload to have a field called `eventName`.   This PR introduces a new config property called `template` which allows a user to specify a simple string template.  Currently the only string that will be interpolated is `${event}`.  Below is an example of a rest endpoint configured with a template.
```
rest:
endpoints:
- wrap: true
url: https://events.spinnaker.myteam.net/
template: '{"myCustomEventFieldName":${event}}'
```
Note that the template must be valid JSON _after_ the interpolation.  The template will contain the event and the entire content details will be placed in `${event}` such that a rendered template will look …
> feat(rest): extensible JSON payloads for Spinnaker events

- echo-rest/src/main/groovy/com/netflix/spinnaker/echo/events/RestEventTemplateEngine.groovy
- echo-rest/src/test/groovy/com/netflix/spinnaker/echo/events/RestEventListenerSpec.groovy
- echo-rest/src/test/groovy/com/netflix/spinnaker/echo/events/SimpleEventTemplateSpec.groovy
This fixes a bug where templating tokens used for rest endpoints collides with Spring based properties.   It currently uses `${event}` although this causes the `/resolvedEnv` endpoint to return the following error:
```
rest.endpoints[0].template":"Exception occurred: Could not resolve placeholder 'event' in string value \"{\"event\":${event}}\"
```
The changes below will instead use double braces  as tokens so a valid configuration will look like the following: 
```
rest:
endpoints:
- wrap: true
url: https://events.spinnaker.myteam.net/
template: '{"myCustomEventFieldName":{{event}} }'
```
> fix(rest) - fixes the tokens used for the rest templates

- build.gradle
Picks up the generic exception handling from `kork-web`
> chore(dependencies): Bump spinnaker-dependencies to 0.101.0

- build.gradle
- echo-pubsub/echo-pubsub.gradle
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/config/EchoPubsubConfigurationProperties.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/config/JedisConfig.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/config/PubsubConfig.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/config/google/GooglePubsubConfig.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/config/google/GooglePubsubProperties.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/config/kafka/KafkaConfig.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/config/kafka/KafkaProperties.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/PollingMonitor.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandler.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubSubscribers.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GoogleMessageAcknowledger.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubMonitor.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubSubscriber.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/kafka/KafkaMonitor.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/kafka/KafkaSubscriber.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/model/MessageAcknowledger.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/model/MessageInstanceDescription.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/model/PubsubSubscriber.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/model/PubsubType.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/utils/NodeIdentity.java
- echo-web/echo-web.gradle
Port of https://github.com/spinnaker/igor/pull/182 to java 8 with its own module into Echo. Recapping what this adds:
* Adds relevant pubsub components as a submodule.
* Adds first pass of Google pubsub polling client.
* Provides stubs for necessary Kafka classes.
* Adds pubsub client synchronization via Redis.
> feat(pubsub): Adds first pass at Google pubsub client.

- echo-notifications/echo-notifications.gradle
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/email/EmailNotificationService.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/NotificationTemplateEngine.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackMessage.groovy
- echo-notifications/src/main/resources/templates/manualJudgment/body-email.ftl
- echo-notifications/src/main/resources/templates/manualJudgment/body-slack.ftl
- echo-notifications/src/main/resources/templates/manualJudgmentContinue/body-email.ftl
- echo-notifications/src/main/resources/templates/manualJudgmentStop/body-email.ftl
- echo-notifications/src/main/resources/templates/pipeline.ftl
- echo-notifications/src/main/resources/templates/stage.ftl
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/ManualJudgmentTemplateTest.groovy
Not much going on here - just bringing in the [commonmark-java](https://github.com/atlassian/commonmark-java) parser to convert markdown to HTML and setting the email message type.
This allows us to render instructions on manual judgment stages in basically the same format in emails as we do in the UI.
Also allowing markdown in Slack messages (it's already supported by Slack, just need to enable it in the message attachment text). Slack only supports a [subset of markdown](https://api.slack.com/docs/message-formatting#message_formatting), but it'll be something users can work through.
@tomaslin PTAL
> feat(notifications): support markdown in slack/email notifications

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/DockerEventMonitor.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/DockerEventMonitorSpec.groovy
When you remove a previously existing regex from the trigger in the
UI, deck keeps a tag field with an empty string for the value in the
json. This arrives as non null to the DockerEventMonitor, which  causes
the trigger to not fire for any new tag until you manually update the
pipeline json to remove the field. This change makes the logic more
resilient to malformed input. Blank or empty tag regex doesn't make
sense so it should behave the same as when the regex is null.
> fix(triggers): fix handling of blank regex in docker registry triggers

- echo-notifications/src/main/resources/templates/appOwnerMultipleUsers/body-email.ftl
- echo-notifications/src/main/resources/templates/appOwnerOutdatedNoSuggestion/body-email.ftl
- echo-notifications/src/main/resources/templates/appOwnerOutdatedReassign/body-email.ftl
- echo-notifications/src/main/resources/templates/appOwnerUnknown/body-email.ftl
- echo-notifications/src/main/resources/templates/appsReassigned/body-email.ftl
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/AppOwnerTemplateTest.groovy
Plain text renders not so great when it's rendered as HTML.
> fix(appOwner): convert app owner emails to html

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitor.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/PubsubEventMonitorSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
Triggers can specify expected artifacts. This change ensures that at least one of the artifacts parsed from the message satisfies each expected artifact specified in the Trigger.
> feat(pubsub): Enforce expected artifacts in triggers.

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgent.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgentSpec.groovy
Allows an entirely custom message to be passed through to Echo via the stage context. I'm exposing two variables with a simple substitution feature: 
* `{{executionId}}` (since that is not known when launching the pipeline)
* `{{link}}` (since that could be useful for deep linking and kind of a pain to construct)
This lets us do things like this:
by adding this to the stage JSON:
```javascript
{
"customMessage": "Fast property update: rolling out property abcd to us-central-1 (step 2 of 3) | <http://localhost:9000/#/applications/deck/properties/{{executionId}}?tab=rollouts&refId=3|link>"
}
```
I'd like to play around with this a bit more and, if it makes sense, add similar functionality to the other notification types (maybe just email).
> feat(slack): allow ad-hoc message publishing via Slack

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/EmailNotificationAgent.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/HipchatNotificationAgent.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgent.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/EmailNotificationAgentSpec.groovy
I put this in Slack and HipChat, but forgot about email. Classic.
Also adding guards around checking for `execution.id`, and allowing `link` replacement, even if `execution.id` is not available.
> fix(email): handle link/executionId replacement in custom email body

- echo-core/echo-core.gradle
- echo-core/src/main/groovy/com/netflix/spinnaker/echo/artifacts/MessageArtifactTranslator.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/artifacts/ArtifactMatcher.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitor.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitor.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandler.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubSubscriber.java
- echo-pubsub/src/test/groovy/com/netflix/spinnaker/echo/pubsub/utils/MessageArtifactTranslatorSpec.groovy
- echo-web/config/echo.yml
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/config/WebhookConfig.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/config/WebhookProperties.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy
The result of this is that if someone POSTs to `$GATE_URL/webhooks/artifacts/<source>` with either
1. `"artifacts": []` specified in the payload, or
2. an artifact transforming jinja template registered for `<source>`.
The artifacts will be injected into any pipelines that declare that webhook (and have matching expected artifacts) as a trigger.
This is useful, because with (1) external systems can either explicitly say which artifacts they want to trigger pipelines with, or, any sort of "push" based trigger system with (2) can have their output converted into something Spinnaker understands without us having to supply code for it.
For example, look at the message format in [quay's notification guide](https://docs.quay.io/guides/notifications.html).
A user (or really us, for common cases …
> feat(webhooks): Support artifacts

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/SlackConfig.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgent.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackAttachment.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackClient.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackMessage.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackNotificationService.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackRequest.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackService.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/config/SlackConfigSpec.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgentSpec.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/slack/SlackServiceSpec.groovy
Fixes https://github.com/spinnaker/spinnaker/issues/2103
This PR adds support for tokens generated for Slack Incoming web hooks [1], which follow this format: `T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX` and target a different Slack API.
This is backward compatible - still works with tokens that rely on chat.postMessage API [2]. 
The implementation is inspired from ansible's slack implementation [3].
Feedback is welcomed. We're using this internally in our environment with success.
[1] https://api.slack.com/incoming-webhooks
[2] https://api.slack.com/methods/chat.postMessage
[3] https://github.com/ansible/ansible-modules-extras/blob/devel/notification/slack.py#L236
> feat(slack): Support slack incoming webhooks

- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandler.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubSubscriber.java
- echo-pubsub/src/test/groovy/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandlerSpec.groovy
@spinnaker/google-reviewers FYI This is a _port_ of https://github.com/spinnaker/echo/pull/201 to 1.5.x. There was a small refactor underneath this fix, so it had to be applied slightly differently on both base branches `master` and `release-1.5.x`.
> fix(pubsub): Use message IDs instead of payload hash. (#201)

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitor.java
We wanted to add the ability for echo webhook triggers to pass on parameters if they are in the webhook payload. We are currently using this endpoint to prevent customization of automagically generated pipelines by using this trigger and tying a service account through RunAsuser that only the thing that can automagically generate pipelines has access to, we do this so that custom pipelines can be created but without impacting generated ones.
It is a bit of a mess but we couldn't really think of a reason why we shouldn't try and contribute this back up as it may be useful for other webhooks potentially.
> Adding ability for custom webhook triggers to pass parameters.

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgent.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/CompactSlackMessage.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackNotificationService.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackService.groovy
We're hearing from users internally that the new Slack message format is unnecessarily verbose, so we are restoring the smaller version of messages as an opt-in feature.
_Without `sendCompactMessages` enabled_
_With `sendCompactMessages` enabled_
> feat(slack): allow more compact slack notifications

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitor.java
Since a user can configure the 'source' of their trigger events, they
should expect that only webhooks to that 'source' actually trigger their
pipeline.
> fix(webhooks): Ensure only matching-source triggers are used

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/OrcaService.java
Adds `getLatestPipelineExecutions` with 3 parameters. It's not used internally with this signature, but our extension is using it.
> feature(OrcaService) add optional query params to getLatestPipelineExecutions

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitor.java
This should fix an issue we ran into with our prior contribution: https://github.com/spinnaker/echo/pull/207
Since events aren't filtered for each pipeline by the point the trigger is built for a pipeline, only the first pipeline processed would have the parameters while the rest would never have them (because we were using remove and not just get).
> fix(webhooks) Webhook trigger events should be treated as immutable.

- echo-model/src/main/groovy/com/netflix/spinnaker/echo/model/trigger/GitEvent.groovy
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/GitEventMonitor.java
@lwander -
The logic that decides to trigger a pipeline with artifacts was looking for the artifacts in `event.payload.artifacts`. But according to this line:
https://github.com/spinnaker/echo/blob/master/echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy#L107
it should be looking in `event.contents.artifacts`.
> fix(artifacts/github): Correctly pull github artifact out of echo event

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/GitEventMonitor.java
Without the artifact being attached to the pipeline, it can not be fetched when the pipeline runs.
> fix(artifacts): Git artifacts should be added to the pipeline.

- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/BuildEventMonitorSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/DockerEventMonitorSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/GitEventMonitorSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitorSpec.groovy
All these tests were in com.netflix.spinnaker.echo.pipelinetriggers.
They are testing classes in
com.netflix.spinnaker.echo.pipelinetriggers.monitor.
This change moves the tests to
com.netflix.spinnaker.echo.pipelinetriggers.monitor as well to match
their corresponding source classes.
> fix(tests): Move tests to correct package as source

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitor.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitorSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
Before this change a webhook payload of
```json
{
"projectId": "warpspeed-playground",
"imageName": "dxia-spinnaker-test",
"imageTag": "0.0.1-SNAPSHOT-20180123T195009-6b82c8e",
"artifacts": [
{
"type": "docker/image",
"name": "gcr.io/image",
"reference": "gcr.io/image"
}
]
}
```
would cause the following error.
```
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.netflix.spinnaker.kork.artifacts.model.Artifact
at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[na:1.8.0_141]
at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[na:1.8.0_141]
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_141]
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) …
```
> fix(webhooks): Correctly deserialize webhook artifacts

- echo-web/etc/init/echo.conf
Changing to appending to the log file so logs will correctly rotate.  This prevents large amounts of null data at the start of a rotated log file.
> fix(echo/log): Append to log instead of overwrite

- echo-pubsub/echo-pubsub.gradle
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/config/JedisConfig.java
- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandler.java
- echo-pubsub/src/test/groovy/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandlerSpec.groovy
Using the redis client delegate to talk to redis so that we can add in dynomite support (coming in a later PR). 
Creating autowired constructor instead of properties.
> refactor(pubsub): adding redisClientDelegate

- echo-pubsub/src/main/java/com/netflix/spinnaker/echo/pubsub/amazon/SQSSubscriber.java
This generates the name in the UI, and should return the user-given name instead of the queue worker name.
> fix(pubsub): changing amazon subscription name

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/EmailNotificationAgent.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgent.groovy
Enhancement to an undocumented feature: allow custom messages (slack, email subject/body) per notification, not just at the entire stage level. This allows more fine-grained custom notifications for stage failures vs. completions.
(We will document this feature once we're happy with it)
> feat(email/slack): allow custom messages per notification

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/PipelineTriggerConfiguration.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitor.java
Wiring this bean up in this way allows us to override it so that we can do custom things with the pubsub trigger.
> feat(trigger): allow pubsub monitor to be overridden

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/BuildEventMonitor.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/DockerEventMonitor.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/GitEventMonitor.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitor.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitor.java
While auditing our echo metrics, I noticed a _huge_ amount of metrics coming in from echo that have very little use. Furthermore, the `name` tag is reserved in Atlas, so the `pipeline.triggered` metric sort of got clobbered.
I removed a couple of the tags, but added `monitor` to track which monitor is actually triggering pipelines.
> fix(pipeline-triggers): Remove high cardinality tags on echo metrics

- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/MissedPipelineTriggerCompensationJobSpec.groovy
Did a light dusting of some cleanup things as well, but nothing functionally changed except the new recurring schedule (every 15 minutes, instead of the daily action that I'd originally proposed in Slack).
> feat(scheduler): Enable compensation job to run regularly, not just on startup

- echo-pubsub-google/echo-pubsub-google.gradle
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubMonitor.java
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubSubscriber.java
Creates a new `Subscriber` on failures, as according to https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1579#issuecomment-282603572 we can `"restart" the Subscriber by creating a new Subscriber object`.
I've also removed `.setMaxAckExtensionPeriod(Duration.ofSeconds(0))` as https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2465#issuecomment-351941181 recommends against it.
Potentially solves https://github.com/spinnaker/spinnaker/issues/2762 but needs more testing. I've verified that echo resumes consuming pubsub messages after I removed its `Pub/Sub Subscriber` permission (took a little while before it noticed) and then added it back again.
> fix(pubsub): Restart Google Pubsub subscriber on failures

- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/MissedPipelineTriggerCompensationJobSpec.groovy
There is a fairly significant logical change in missedExecution to account
for last executions outside the lookback window.
Other changes:
* new test cases
* don't use a gauge
* jazz up logging
* make the polling interval and pipeline fetch size configurable
* keep bailing for pipelines that don't have a last execution -- not
strictly necessary, but seems safer
> fix(cron): make comp job work for hourly/daily pipelines

- README.md
- build.gradle
Starting echo with ./gradlew -DDEBUG=true now causes the JVM to
listen on port 8189 for a remote debugger.
> chore(build): Add debug flag to echo build

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/PipelineConfigsPollingAgent.groovy
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/PipelineTriggerConverter.groovy
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/TriggerRepository.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineConfigsPollingAgentSpec.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineTriggerActionConverterSpec.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/TriggerRepositorySpec.groovy
If pipeline configurations with null cron trigger ids somehow went past
front50, we would have "flagging" registrations: new triggers would be found,
then on the next pass of the PipelineConfigsPollingAgent we would find
scheduled actions with no corresponding triggers (since they don't have)
a matching id. We would then deregister then, only to register them again
right away, and so on.
With this change, we no longer need a persisted id for cron triggers in
the pipeline configurations (which is bound to be messed with, deleted,
copied, mangled...)
> fix(cron): fallback for cron triggers with null id

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCacheSpec.groovy
Break the cycle by ignoring the Trigger.parent field in the output.
> fix(json): prevent infinite recursion when serializing pipelines

- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/config/GooglePubsubProperties.java
- echo-rest/src/main/groovy/com/netflix/spinnaker/echo/config/RestProperties.groovy
As of Spring Boot 1.5, `@ConfigurationProperties` classes that use constraint annotations should also be annotated with `@Validated`; this is currently throwing warnings but may actually break in the future.
> fix(build): Fix spring warnings about validated classes

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitor.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/TriggerMonitor.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitorSpec.groovy
This change causes the pubsub event processor to wait until pipelines have been polled at least once before processing pubsub messages.  This fixes a race condition whereby pubsub messages that were received immediately after startup were not triggering any pipelines.
> fix(pubsub): Wait until pipelines are loaded to process pubsub messages

- build.gradle
- echo-pipelinetriggers/echo-pipelinetriggers.gradle
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/PipelineTriggerConfiguration.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiatorSpec.groovy
- echo-web/src/main/groovy/com/netflix/spinnaker/echo/filters/EchoCorsFilter.groovy
This allows for fiat to be selectively enabled at runtime via the
DynamicConfigService (environment-specific).
`s/CorsFilter/EchoCorsFilter` to get around an equivalently named bean
in spring boot.
> feat(fiat): Delegate whether fiat is enabled to `FiatStatus`

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/artifacts/ArtifactMatcher.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/artifacts/ArtifactMatcherSpec.groovy
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/AmazonMessageAcknowledger.java
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriber.java
- echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandler.java
The logging around pubsub is a little excessive. I'd like to trim down the log messages produced and rely on emitting metrics for number of messages processed etc.
Also adding tests for ArtifactMatcher and adding clarifying text around usage of `isConstraintInPayload`
> chore(logs+tests): removing excessive logging, adding tests

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
This field is used by pipeline triggers (in orca) to determine what status pipeline to trigger off of.
> feat(trigger): adds pipeline trigger status field

- Dockerfile.slim
`useradd` was causing build errors:
```
...
Step 5/7 : RUN useradd -m spinnaker -U
---> Running in 7fabf6d609a4
/bin/sh: useradd: not found
```
so I fixed it match the other services.
ex:
igor: https://github.com/spinnaker/igor/blob/master/Dockerfile.slim#L9
clouddriver: https://github.com/spinnaker/igor/blob/master/Dockerfile.slim#L9
orca: https://github.com/spinnaker/orca/blob/master/Dockerfile.slim#L9
> fix(docker): fixed command to add spinnaker user

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/email/EmailNotificationService.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/email/EmailNotificationServiceSpec.groovy
Handle the situation where someone has configured a notification with
' '-separated email addresses (vs. presumably comma separation).
> fix(notifications): Support email notifications with ' ' in them

- build.gradle
BREAKING CHANGE: This change affects the way in which artifacts injected
into a pipeline are matched to expected artifacts. Prior to this change,
a match was successful if the regular expression in the expected artifact
matched any substring of the corresponding field in the incoming artifact;
after this change, the regular expression in the expected artifact must
match the entire corresponding field incoming artifact.
As an example, consider an incoming artifact with name 'artifact123'. Before
this change, it would match expected artifacts with names 'artifact' and
'artifact.*'.  After this change, the incoming artifact will no longer
match an expected artifact with name 'artifact' but will continue to match
'artifact*'; users will need to explicitly add a wildcard (or some more
complex …
> feat(artifacts): Artifact matching should use entire string

- .gitignore
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/BuildEventMonitor.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/BuildEventMonitorSpec.groovy
- echo-test/src/main/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
Wercker CI Feature: 
- Added "wercker" to the list of known Build Trigger Types
Related PRs: 
https://github.com/spinnaker/halyard/pull/960
https://github.com/spinnaker/igor/pull/297
https://github.com/spinnaker/deck/pull/5519
https://github.com/spinnaker/gate/pull/574
https://github.com/spinnaker/orca/pull/2313
@markxnelson
> feat(trigger/wercker): Add wercker trigger

- echo-core/src/main/groovy/com/netflix/spinnaker/echo/artifacts/DefaultJinjavaFactory.java
- echo-core/src/main/groovy/com/netflix/spinnaker/echo/artifacts/JinjavaFactory.java
- echo-core/src/main/groovy/com/netflix/spinnaker/echo/artifacts/MessageArtifactTranslator.java
- echo-core/src/main/groovy/com/netflix/spinnaker/echo/config/EchoCoreConfig.groovy
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriber.java
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriberProvider.java
- echo-pubsub-aws/src/test/groovy/com/netflix/spinnaker/echo/pubsub/aws/AmazonSQSSubscriberSpec.groovy
Doing this so that you can add custom jinja filters and tags in and load them. No change in functionality from a google or pubsub perspective, I'm just building off of it for a custom trigger.
> feat(pubsub): allow custom jinjava

- echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandler.java
- echo-pubsub-core/src/test/groovy/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandlerSpec.groovy
Make `redisClientSelector` optional so that if pubsub is not enabled echo actually starts up. 
Throw exception when redis is not enabled but pubsub is.
> fix(pubsub): echo starts up when pubsub not enabled

- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineTriggerAction.groovy
Apologies about fixing the formatting. 
Only change here is wiring in the `Registry` and then publishing a metric:
```java
Id id = registry.createId("pipelines.triggered")
.withTag("monitor", getClass().getSimpleName())
.withTag("application", Optional.ofNullable(pipeline.getApplication()).orElse("NULL_APPLICATION"))
registry.counter(id).increment()
```
> chore(metrics): add cron pipeline started metric

- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/config/AmazonPubsubProperties.java
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/AmazonMessageAcknowledger.java
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/MessageAttributeWrapper.java
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/NotificationMessageWrapper.java
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriber.java
- echo-pubsub-aws/src/test/groovy/com/netflix/spinnaker/echo/pubsub/aws/AmazonSQSSubscriberSpec.groovy
When you set message attributes on an SNS message, and then an SQS queue pulls that message, the message attributes aren't translated to the SQS message attributes field. Instead, they're in a `MessageAttributes` map on the message body. 
Adding the ability to parse sns message attributes and add them to the list of message attributes.
In order to dedupe client messages as well as sqs messages, I'm allowing you to provide an id to dedupe with. This will be present in a message attribute field with key `id`, like below:
```
pubsub:
amazon:
enabled: true
subscriptions:
- name: echo_events
topicARN: arn:aws:sns....
queueARN: arn:aws:sqs....
templatePath: /sqs.jinja
idInMessageAttributes: true #this is the new, optional field
```
This will still work with at least once delivery because any …
> feat(pubsub): add sqs msgattr parsing, optional id in msgattrs

- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/config/AmazonPubsubProperties.java
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriber.java
- echo-pubsub-aws/src/test/groovy/com/netflix/spinnaker/echo/pubsub/aws/AmazonSQSSubscriberSpec.groovy
Instead of assuming the field is `id`, allow specification of the field name.
> feat(pubsub): allow alternate id in msg attrs and define key

- echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/config/JedisConfig.java
I accidentally made the default true. It should be false for echo, since redis is only required for pubsub.
> fix(redis): default to redis.enabled:false like before

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/pubsub/MessageDescription.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitorSpec.groovy
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/config/AmazonPubsubProperties.java
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriber.java
- echo-pubsub-aws/src/test/groovy/com/netflix/spinnaker/echo/pubsub/aws/AmazonSQSSubscriberSpec.groovy
- echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandler.java
- echo-pubsub-core/src/test/groovy/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandlerSpec.groovy
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubSubscriber.java
- echo-test/src/main/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
We use Dynomite internally, and the `psetex` command is not implemented. Switching to seconds here, and `setex` (which is supported for us). Sound ok?
> chore(pubsub): switch to seconds and setex redis command

- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/config/AmazonPubsubConfig.java
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/config/GooglePubsubConfig.java
If a particular echo profile wants to disable all pubsub, it currently
needs to do it for each pubsub provider. This is brittle, as new pubsub
providers may be added later.
It can now be disabled globally with
pubsub:
enabled: false
> chore(pubsub): add a global enable flag for pubsub

- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/MissedPipelineTriggerCompensationJobSpec.groovy
... instead of all triggers, this should restrict the query to triggers
that have a valid fire time in the compensation window.
> feat(cron): only query execution history for eligible triggers

- echo-core/src/main/groovy/com/netflix/spinnaker/echo/services/Front50Service.java
- echo-core/src/main/groovy/com/netflix/spinnaker/echo/services/GraphQLQuery.java
- echo-core/src/main/groovy/com/netflix/spinnaker/echo/services/GraphQLQueryResponse.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java
An experimental front50/graphql integration. The schema
exposed by front50 only really supports pipelines with
cron triggers. Similarly, we haven't implemented a query
builder or anything of that sort on the Echo side.
Should we see positive results from this integration,
a more focused effort will be put in to offer a more
fully featured integration.
Usage:
```java
GraphQLQueryResponse resp = front50.query(GraphQLQuery.pipelines("cron"));
```
> feat(core): Front50 graphql client

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/ManualEventMonitor.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/TriggerMonitor.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/BuildEventMonitorSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/DockerEventMonitorSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/GitEventMonitorSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/PubsubEventMonitorSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/monitor/WebhookEventMonitorSpec.groovy
Two changes:
* Change the fix I made in https://github.com/spinnaker/echo/pull/274 so that we block waiting for the initialization of the pipeline cache instead of having RxJava defer the operation and perform it on the pipeline cache thread.  This is necessary to properly pass authentication headers through Echo.
* Remove some RxJava from `TriggerMonitor.java`
Keeping these as separate commits as I may want to pull the fix into 1.10 so that my new manual trigger workflow works there without a race condition on startup.
>  fix(core): Ensure event processing occurs in the same thread

- echo-notifications/echo-notifications.gradle
- echo-pipelinetriggers/echo-pipelinetriggers.gradle
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/DockerEventHandler.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/GitEventHandler.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/PubsubEventHandler.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/health/MonitoredPollerHealth.java
- echo-scheduler/echo-scheduler.gradle
Reduce transitive dependencies in echo-pipelinetriggers by explicitly specifying dependencies, and remove any unused dependencies.
Explicitly include the following, which were transitively included before:
* echo-model
* korkArtifacts
* jacksonDatabind
* springContext
* commons-lang (pull in lang3, and update calls from lang)
Remove the following, which are not needed:
* guava (unused)
* okHttp (part of retrofitDefault group)
* eurekaClient (unused)
* groovy (only in test module now and included in test group)
* spock (included in test group)
Update two other modules to explicitly pull in logstashEncoder as they were transitively depending on it being in echo-pipelinetriggers
> refactor(core): Clean up echo-pipelinetriggers dependencies

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/PipelineTriggerConfiguration.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/QuietPeriodIndicatorConfigurationProperties.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/QuietPeriodIndicator.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/QuietPeriodIndicatorSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiatorSpec.groovy
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/impl/MissedPipelineTriggerCompensationJob.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/MissedPipelineTriggerCompensationJobSpec.groovy
This change allows a single quiet period to be defined in the echo config:
```yaml
quietPeriod:
enabled: true
startIso: 2018-11-20T00:00:00Z
endIso: 2019-01-15T00:00:00Z
suppressedTriggerTypes:
- jenkins
- cron
```
This causes Echo to not allow triggers of those types to start a pipeline if the current time is within the defined time range (inclusive).  No notices beyond log messages will be made that it was suppressed, so nothing will be shown to the user.
A change for deck will be coming up, as well as adding this pipeline flag to Orca's pipeline model once this is approved.
> feat(quiet-periods): optionally supress triggers during quiet periods

- echo-notifications/src/main/resources/templates/swabbie/body.ftl
Adding that the resource isn't in use to main email text.
Adding the time the resource was created so that when you receive the email you know the resource is old.
Changing opt out button to be "opt out of delete" because there was confusion whether this meant opt out of emails or opt out of delete.
> feat(swabbie): update email based on feedback

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ArtifactPostProcessor.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ArtifactPostProcessorSpec.groovy
As a first pass, let's allow users to select a Jinja template to extract artifacts from a Jenkins job by exporting the template to use as a property. We'll likely want to provide other ways of configuring this in the future, but this is a lightweight way to get started, and will allow users to start using this feature.
> feat(artifacts): Use property to select template

- echo-pipelinetriggers/src/main/resources/jar.jinja
Adds the ability to set an optional classifier on a jar artifact. Also changes the artifact type from jar/archive to repotype/file where repotype defaults to maven.
> feat(artifacts): Add classifier to jar artifact

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
When a request to Orca to start a pipeline fails, Echo currently retries a number of times (defaulting to 5). In cases where the failure is due to a problem with the request, we should not retry; gate the retry logic so that we don't retry when receiving a 400 - Bad Request from Orca. In particular, this will stop having pipelines missing artifacts lead to 5 failed executions in the history.
See also https://github.com/spinnaker/orca/pull/2524
> fix(core): Don't retry pipeline initiation when receiving a 400

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackClient.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/slack/SlackServiceSpec.groovy
Since the request URL gets logged with the default configuration, let's put the token in the request body.
There is still an issue that using the incoming webhook approach probably logs the token; I will leave that as an exercise for someone who uses that to fix.
> fix(slack): send token on postMessage in request body

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
Some workflows (ex: manual triggers specifying a docker tag) directly inject artifacts into the trigger; we need to add an artifacts field to the Trigger model so that these work properly.
> fix(artifacts): Fix artifact population in manual triggers

- echo-core/src/main/java/com/netflix/spinnaker/echo/services/IgorService.java
Jenkins requires build names containing slashes to be sent with the slashes unencoded.
> fix(jenkins): Fix encoding of Jenkins URL

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ArtifactPostProcessor.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ArtifactPostProcessorSpec.groovy
When parsing the customFormat supplied in the property file, we currently assume it is a string. If the property file is supplied as YAML, it could be a boolean.
> fix(artifacts): Allow customFormat to be a boolean

- echo-pubsub-google/src/main/resources/gcb.jinja
We're able to extract more artifacts than we currently do from Cloud Build pubsub messages.
> feat(pubsub): update GCB transform template to extract more artifacts

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/trigger/WebhookEvent.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/WebhookEventHandler.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/WebhookEventHandlerSpec.groovy
- echo-test/src/main/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
- echo-web/config/echo.yml
Less use of after-the-fact `ObjectMapper` off of untyped properties.
> refactor(eventhandlers): specify WebhookEvent content expectations in its type

- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy
- echo-webhooks/src/test/groovy/com/netflix/spinnaker/echo/controllers/WebhooksControllerSpec.groovy
Since Bitbuckets Server hooks are different from Bitbucket Cloud, now also
add support for the former, so can be triggered with on-prem.
> feat(artifacts/bitbucket): Accept Bitbucket Server hooks

- echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubSubscriptionController.java
- echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/model/PubsubPublisher.java
- echo-pubsub-google/echo-pubsub-google.gradle
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/config/GooglePubsubConfig.java
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/config/GooglePubsubProperties.java
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubNotificationEventListener.java
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubPublisher.java
part of https://github.com/spinnaker/spinnaker/issues/2784
We used to have a operator-defined `name` field, but I took it out in the last revamp. Adding it back in to support the (probably?) niche use case of the same topic name in different projects.
This means that in order to trigger notifications, we match on `publisherName` instead of `topic` in the incoming notification map.
> fix(pubsub): Reintroduces 'name' field to google pubsub publishers

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/artifacts/StandardJinjaTemplate.java
- echo-pipelinetriggers/src/main/resources/docker.jinja
Provides a standard artifact extraction template to extract a Docker
image artifact from build properties.
Example property file:
```properties
image=path/to/registry:tag
messageFormat=DOCKER
```
> feat(artifacts): Artifact extraction template for Docker

- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/GithubWebhookEventHandler.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/GitlabWehbookEventHandler.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/StashWebhookEventHandler.java
cleans up unnecessary annotations in `SCMWebhookHandler`
implementations.
> chore(webhooks): cleanup unnecessary annotations

- echo-pipelinetriggers/echo-pipelinetriggers.gradle
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ExpectedArtifactExpressionEvaluationPostProcessor.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/PostProcessorPriority.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ExpectedArtifactExpressionEvaluationPostProcessorSpec.groovy
Echo will now attempt to evaluate any SpEL expressions in expected artifact inputs prior to matching against trigger artifacts.
> feat(expressions): Allow SpEL expressions in expected artifacts

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ExpectedArtifactExpressionEvaluationPostProcessor.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ExpectedArtifactExpressionEvaluationPostProcessorSpec.groovy
While the UI always populates expectedArtifacts on new pipelines, this isn't enforced server-side so it's possible for a pipeline to have null expectedArtifacts.
Our integration tests were throwing an NPE when trying to start pipelines without expectedArtifacts explicitly set.
> fix(expressions): Fix NPE in artifact expression evaluation

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
The Pipeline model is missing keepWaitingPipelines, which means it's ignored on deserialization and setting it on a pipeline has no effect.
> fix(pipelines): Add keepWaitingPipelines to Pipeline model

- echo-core/echo-core.gradle
Hi folks, this happened between gradle 4 and 5:
> Gradle 4.6 (Released 2018-02-28) deprecated annotation processors on the compile classpath in favor of the new annotationProcessor configuration to improve incremental compilation performance. In Gradle 5.0 annotation processors have moved to their own configuration.
lombok dependency comes as transitive in compile configuration from echo-core -> https://dl.bintray.com/spinnaker/spinnaker/com/netflix/spinnaker/echo/echo-core/1.585.2/echo-core-1.585.2.pom
```<dependency>
<groupId>org.projectlombok</groupId>
<artifactId>lombok</artifactId>
<version>1.16.20</version>
<scope>compile</scope>
</dependency>```
If someone has an application which uses `echo-core` and tries to use `lombok` from it's transitive dependency, it will fail because it …
> Use annotationProcessor scope for lombok

- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/config/SchedulerConfiguration.groovy
Making sync trigger optional so that the scheduler can run with only the compensation job
> fix(trigger): Fixing mistake in #481

- echo-core/src/main/java/com/netflix/spinnaker/echo/build/BuildInfoService.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BuildEventHandler.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ManualEventHandler.java
Manual triggers currently don't pass along build artifacts from the 'artifacts' field of the build (as opposed to jinja-extracted artifacts which they do). Update them to do so, making it possible to remove the [special-case logic in Orca](https://github.com/spinnaker/orca/blob/b549b58c213220b604860d9e4625e0ef5296312d/orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy#L281) to handle this.
This commit also pushes some logic from the build handler to the `BuildInfoService` so it can be shared.
> refactor(triggers): Improve code sharing for manual and build triggers

- echo-pubsub-google/src/main/resources/gcb.jinja
The GCB artifact extractor currently includes the tag in the image name; this conflicts with the general convention of excluding it and leads to issues matching incoming artifacts and replacing artifacts in manifests. Fix this to only include the image name.
> fix(pubsub/google): Remove tag from image name

- echo-core/src/main/java/com/netflix/spinnaker/echo/artifacts/ArtifactInfoService.java
- echo-core/src/main/java/com/netflix/spinnaker/echo/config/ArtifactInfoConfig.java
- echo-core/src/main/java/com/netflix/spinnaker/echo/config/BuildInfoConfig.java
- echo-core/src/main/java/com/netflix/spinnaker/echo/services/IgorService.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ManualEventHandler.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ManualEventHandlerSpec.groovy
Make config for build and artifact services explicit.
Add a function to resolve artifacts.
If a manual trigger body looks like:
```
"trigger": {
"type": "manual",
"dryRun": false,
"user": "emburns@netflix.com",
"artifacts": [{
"name": "my-package",
"version": "v1.1.1",
"location": "artifactory"
}]
}
``` 
Then we will try to resolve the artifact. If that artifact doesn't exist, or you don't have any providers which match the location in `igor`, then the artifact won't be found and it will be removed from the manual trigger. 
@jkschneider for the manual artifactory trigger you'll need to implement lookup logic in `igor` and the ui bits that will add this half fleshed out artifact into the manual trigger.
@ezimanyi thoughts on if using the artifacts field on the trigger to provide a …
> feat(artifacts): populate artifacts for manual trigger

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java
For some reason we had a malformed pipeline with a null name (old). After this PR (https://github.com/spinnaker/echo/pull/504/files#diff-123d58ccbba1de00453419d04e10722e) echo wouldn't start up with that. This adds some logging and filtering to continue ignoring that malformed pipeline, just in case...
> fix(pipeline): if map -> Pipeline fails, log and move on

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ManualEventHandler.java
We were seeing occasional NPE's during manual execution:
```
java.lang.NullPointerException: null
at com.netflix.spinnaker.echo.pipelinetriggers.eventhandlers.ManualEventHandler.buildTrigger(ManualEventHandler.java:111) ~[echo-pipelinetriggers.jar:na]
at com.netflix.spinnaker.echo.pipelinetriggers.eventhandlers.ManualEventHandler.withMatchingTrigger(ManualEventHandler.java:85) ~[echo-pipelinetriggers.jar:na]
at com.netflix.spinnaker.echo.pipelinetriggers.eventhandlers.ManualEventHandler.withMatchingTrigger(ManualEventHandler.java:49) ~[echo-pipelinetriggers.jar:na]
at com.netflix.spinnaker.echo.pipelinetriggers.eventhandlers.TriggerEventHandler.lambda$getMatchingPipelines$0(TriggerEventHandler.java:67) ~[echo-pipelinetriggers.jar:na]
at …
```
> fix(events): Guard against NPE when artifacts is not set.

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
We saw that manual triggering of V1 pipelines stopped working because schema wasn't being set correctly.
More specifically, echo gets a pipeline and then calls out to orca to plan. On this conversion (https://github.com/spinnaker/orca/blob/master/orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePreprocessor.kt#L62) the `objectMapper` is not correctly pulling out the `schema` field from the `config` map (https://github.com/spinnaker/orca/blob/master/orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/TemplatedPipelineRequest.java#L42). This used to not be a problem because in echo `Pipeline` did not have `schema` field (introduced in https://github.com/spinnaker/echo/pull/504/files). Adding `schema` to the echo …
> fix(mpt): fix planing of v1 pipelines for manual triggers

- echo-rest/src/main/groovy/com/netflix/spinnaker/echo/events/RestEventListener.groovy
- echo-rest/src/test/groovy/com/netflix/spinnaker/echo/events/RestEventListenerSpec.groovy
Currently we log the whole event first which can be quite large and thus overloads our log provider (truncating the message)
Split the log into parts such as the important bits are first and the rest can get truncated
> refactor(logging): Log better messages when events fail

- echo-artifacts/src/main/java/com/netflix/spinnaker/echo/config/KeelConfig.java
- echo-core/src/test/groovy/com/netflix/spinnaker/echo/services/Front50ServiceSpec.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/BearychatConfig.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/DryRunConfig.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/GithubConfig.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/GoogleChatConfig.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/HipchatConfig.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/JiraConfig.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/PagerDutyConfig.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/SlackConfig.groovy
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/IgorConfig.java
- echo-web/src/main/java/com/netflix/spinnaker/echo/config/Front50Config.java
GSON is the default converter. It, for some reason, takes a perfectly valid JSON
with integers and parses them as doubles (sometimes). Jackson doesn't do that.
Jackson is better, use it.
> fix(retrofit): make sure all retrofit clients use Jackson

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ManualEventHandler.java
If the trigger payload has a `job` and `master` but not the `buildNumber`
echo will fail to kick off a pipeline without any warning
> fix(triggers): Ensure build number is present

- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriber.java
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriberProvider.java
- echo-pubsub-aws/src/test/groovy/com/netflix/spinnaker/echo/pubsub/aws/AmazonSQSSubscriberSpec.groovy
- echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubEventCreator.java
- echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandler.java
- echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/model/EventCreator.java
- echo-pubsub-core/src/test/groovy/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandlerSpec.groovy
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/config/GooglePubsubConfig.java
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubSubscriber.java
* feat(pubsub): Send pubsub events through eventPropagator 
Currently all pubsub events are sent directly to the trigger event listener, rather than to the general eventPropagator (which notifies all event listeners). This means that pubsub events can never do anything other than start pipelines. (Other incoming events, such as webhooks or build notifications are sent to the general eventPropagator.)
In order to allow pubsub messages to do other things than start pipelines, send the resulting event to the eventPropagator so that other listeners can act on these events.
* refactor(pubsub): Encapsulate logic for creating events 
The logic for extracting artifacts from pubsub events and for creating events from the message is embedded in the logic for handling these messages. In order to …
> refactor(pubsub): Encapsulate logic for creating events

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.groovy
We're now logging all pubsub events in AbstractNotificationAgent; given the volume of these events, turn off this logging for pubsub.
> fix(pubsub): Don't log all pubsub events

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BaseTriggerEventHandler.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ManualEventHandler.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/TriggerEventHandler.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BuildEventHandlerSpec.groovy
A pipeline with 2 triggers and an event matching one of them could
actually be triggered twice. The problem is that withMatchingTrigger
would consider the event and all triggers of the pipeline, and it would
be called once for each trigger.
The key fix is to matchTriggerFor(event) in getMatchingPipelines().
As a result, we can change the inputs of getMatchingPipelines to an event
and a matching trigger instead of an event and a pipeline (with all its
triggers).
> fix(triggers): prevent double-triggering for pipelines with >1 triggers

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiatorSpec.groovy
Echo and externally triggered (via `gate`) pipelines differ in that the
former does not propagate `X-SPINNAKER-ACCOUNTS`, even when a service
account is being used.
When `services.fiat.legacyFallback` is enabled, this PR will fetch
the allowed accounts for either the specified service account name
or `anonymous`.
The goal is to make fallbacks consistent regardless of how a pipeline
was triggered.
> feat(auth): Propagate `X-SPINNAKER-ACCOUNTS` when triggering pipelines

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BaseTriggerEventHandler.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ArtifactoryEventHandlerSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BuildEventHandlerSpec.groovy
This has always been the behavior so far, but matching events on a per
trigger basis (introduced recently) could result in a multiple triggers
matching for the same pipeline. I could not think of a case where this
was an actually desired outcome, so let's keep the existing behavior.
> fix(triggers): avoid single event causing >1 executions of same pipeline

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
These are used in pipeline triggers of type "pipeline". Since the Trigger
model did not know about these fields, it caused duplicate ids to be
generated for these triggers, and made debugging harder/toString less
useful.
> chore(triggers): add application and pipeline fields to Trigger

- echo-web/echo-web.gradle
- echo-web/src/main/java/com/netflix/spinnaker/echo/Application.java
In the Spring Boot 2 upgrade, `spring.config.location` overrides all other config locations. The equivalent property is now called `spring.config.additional-location`.
This fix allows the app the to run without additional config files.
> fix(core): Spring does not override default configuration files.

- echo-core/src/main/java/com/netflix/spinnaker/echo/services/IgorService.java
- echo-pubsub-google/echo-pubsub-google.gradle
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/config/GoogleCloudBuildConfig.java
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GoogleCloudBuildArtifactExtractor.java
Extracting artifacts using a Jinja template does not properly work when a GCB build produces GCS artifacts. This is because the build saves a manifest file to GCS, and we need to read the manifest file to find the location of each produced artifact.
The functionality to do this was recently added to igor; if we're listening to a GCB pubsub topic, use a custom artifact extractor that asks igor to get the artifacts from the build.
> feat(gcb): Call igor to extract artifacts when triggering

- echo-scheduler/echo-scheduler.gradle
`quartz` now comes from spring bom (pulled in by kork-bom).
Remove the unnecessary pinning of `quartz` (it doesn't work the way it is anyway)
Note: this means that CRON expressions that use step value of 60 (for mins/secs)
or 24 (for hours) will no longer work (it wasn't valid before but previous `quartz`
was less strict about the validation).
There shouldn't be many users affected (if at all) because
a) these are non standard CRON expression anyway
b) most users "write" their expressions from the UI which wouldn't generate these.
We will have a release note for Spinnaker 1.14 about this.
> chore(*): Remove stale comments from gradle file

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/email/EmailNotificationService.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/email/EmailNotificationServiceSpec.groovy
If a pipeline specified two email addresses in the notification that email notification
will not be sent.
This change moves the email address splitting/parsing logic to the least common denominator -
the `send` function since it can be called either by handling an email event directly or
indirectly via pipeline/stage events
Also, adding the ability to split on semicolons in email addresses
> fix(email): fix email parser to not fail on multiple addresses

- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/ScmWebhookHandler.java
handle an NPM when calling the webhook controller with an invalid
source.
> fix(webhooks): handle NPE when source invalid

- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/controllers/WebhooksController.groovy
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/ScmWebhookHandler.java
handle an NPM when calling the webhook controller with an invalid
source.
Cherry-pick of spinnaker/echo#552
> fix(webhooks): handle NPE when source invalid (#552)

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiatorSpec.groovy
previous change (https://github.com/spinnaker/echo/pull/555) moved orca invocation
to an executor thread without propagating MDC context.
> fix(auth): propagate MDC across the thread boundary for pipeline execution

- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriber.java
If we fail to initialize the queue, everything fails silently. This will log the exception and then continue to fail.
> fix(awspubsub): add error logging

- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/BitbucketWehbookEventHandler.java
There are rare cases (often when the /bitbucket endpoint is used instead
of /stash) where the bitbucket event type doesn't match _either_ the
Cloud or Server types; this can cause an NPE in the subsequent log
message because "branch" doesn't get set (this was also fixed, although
should probably not happen any more).  In this case, we log the fact
that we couldn't determine the Cloud/Server type based on the event_type
(noting the event_type we _did_ get) and return.
> fix(bitbucket): Log when Bitbucket event unknown

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ManualEventHandler.java
Fixes spinnaker/spinnaker#4548.
If the name or application on a trigger is null, we throw an NPE.  This only happens in the 1.12.x branch, as in 1.13 and beyond the @NonNull annotation on these fields is causing invalid pipelines to fail to deserialize and we thus never check them against triggers.
Add null checks to the 1.12 branch directly to fix the issue here. I'd rather not add these checks in later branches as having the field annotated as @NonNull is a better fix and it's redundant to perform a lot of null checks against @NonNull fields.
> fix(triggers): Fix NPE on null application/name

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/api/Notification.groovy
HIPCHAT was removed from the Enum here, but this enum is duplicated in
other microservices (for example, in Orca,
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/EchoService.groovy
has a copy of the list)
This is a quick fix to repair the numbering scheme.  This should
probably be fully refactored so the enum is either a) specifying actual
values for each type so they maintain consistency going forward, b)
unify in kork somehow, or c) both.
> fix(notifications):  Need to maintain enum order

- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/config/SchedulerConfiguration.groovy
it seems that `read-committed` on mysql doesn't have strong enough locking for
quartz to ensure only one clustered instance picks up a given cron trigger.
[Documentation](http://www.quartz-scheduler.org/documentation/quartz-2.1.7/configuration/ConfigJobStoreTX.html) suggests to set `acquireTriggersWithinLock` to `true`
(also see https://github.com/quartz-scheduler/quartz/issues/107)
> fix(cron): fix to not fire the same cron job on multiple instances

- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/GithubWebhookEventHandler.java
- echo-webhooks/src/test/groovy/com/netflix/spinnaker/echo/controllers/WebhooksControllerSpec.groovy
Some Git webhooks don't have a "ref" field, which is assumed in this
handler.  Sets the branch to empty string in this case (presuming other
code is expecting to find a non-null value further downstream).
> fix(webhooks):  Test for empty ref on Git hooks

- build.gradle
- echo-bom/echo-bom.gradle
compileOnly dependency should not be added to generated pom.xml,
see discussion: https://discuss.gradle.org/t/publishing-plugin-should-respect-compileonly-configuration/22903/2
see related commit: nebula-plugins/nebula-publishing-plugin@a5432aa
> fix(bom): Fix generated pom.xml to omit invalid lombok declaration

- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/BitbucketWehbookEventHandler.java
Use equals for string comparison on bitbucket server event types.
This is currently causing that pipelines configured to automatically trigger on bitbucket server git changes to not get executed.
> fix(bitbucket): use equals for string comparison on event_type

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/GoogleCloudBuildNotificationAgent.java
- echo-pubsub-google/echo-pubsub-google.gradle
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GoogleCloudBuildArtifactExtractor.java
Since the GCB functionality was written, we've started logging messages every time an intra-microservice call is anonymous. When calling igor in response to a PubSub message, we don't have any authentication context and need to make an anonymous call, so wrap these calls in an allowAnonymous call.
> fix(gcb): Allow anonymous calls to igor

- echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/utils/NodeIdentity.java
- We noticed timeouts while running this locally on VPN , bumping the value to `500` ms to help with local runs
> fix(pubsub): Increase socket timeout

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackNotificationService.groovy
Adds debug-level logging for Slack notifications, useful for debugging Slack integration problems (authentication errors, etc).
Resubmitted/Rebased PR (ref.  https://github.com/spinnaker/echo/pull/588 )
> refactor(slack):  Add trace logging of Slack responses

- echo-web/echo-web.gradle
- echo-web/src/main/java/com/netflix/spinnaker/echo/Application.java
Adds support for loading account info (e.g. for pubsub accounts) from an external Spring Cloud Config source. See https://docs.google.com/document/d/16EWk-ChZkae87hCSCFdl3ElepTLC-ac-4uv1tCyfZcc/edit#heading=h.dxx7kr140erk
> feat(core): Use Spring Cloud Config for external configuration of accounts

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ManualEventHandler.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/TriggerMonitor.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/OrcaService.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
We need a way to indicate failures in materializing a pipeline.
If `echo` fails to materialize a pipeline during a trigger the failure needs to be recorded
in `orca` otherwise, the failure appears "silent" to the user because the UI is unable to
show any errors unless they are associated with an execution.
This is especially bad if, say, there is a typo in the properties file in the jenkins trigger
Starting the pipeline appears to do nothing and the user is confused.
This change captures errors during artifact resolution and sends them to `orca` to capture for the user
>NOTE: depends on related `orca` PR: https://github.com/spinnaker/orca/pull/3126
> fix(error handling): mark executions failed

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackNotificationService.groovy
was causing slack notifications to repeat endlessly as the notification would be
sent, but the log statement afterwords would fail and return an error back to
orca which would retry.
> fix(notification/slack): fix missing logger

- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/GoogleChatNotificationAgentSpec.groovy
It wasn't running because it didn't have `extends Specification`.
> test(google): Enable the GoogleChatNotificationAgent test

- echo-telemetry/echo-telemetry.gradle
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/TelemetryEventListener.java
- echo-telemetry/src/test/groovy/com/netflix/spinnaker/echo/telemetry/TelemetryEventListenerSpec.groovy
- echo-web/config/echo.yml
- halconfig/echo.yml
This should prevent sending pings to the stats collector in case the environment is air gapped or the endpoint is actually down. 
Side note: resilience4j is pretty neat, and 1.0.0 was just released. Opened https://github.com/spinnaker/kork/pull/382 to add `resilience4j-circuitbreaker` to the next kork release.
Fixes https://github.com/spinnaker/spinnaker/issues/4864
> feat(stats): Adds circuit breaker logic via resilience4j

- echo-scheduler/echo-scheduler.gradle
This change allows a custom build of Spinnaker to exclude the `mysql-connector-java` driver from the generated distribution with a build command like:
`./gradlew echo-web:installDist -x test -PexcludeSqlDrivers`
The driver is included in the build by default, so the build results are not changed for existing open-source and custom builds. 
The Gradle dependency types were changed from `implementation` to `runtimeOnly` to reflect the fact that `mysql-connector-java` is not needed for compilation.
> feat(sql): Conditionally allow MySQL Connector to be excluded from the build

- .gitignore
fix to build images using `cloud builds`
when I attempt to build using gcloud `gcloud builds submit ....` the  archive file uploaded does not include the `build` package. the line in the `.gitignore` `*/build/"` is being used to ignore the package. 
Work around is to white list the package directory.
filed a bug with gcloud build:
https://issuetracker.google.com/issues/141435398
> fix(build): whitelist build package to avoid being ignored by gcloud cloudbuild

- echo-telemetry/echo-telemetry.gradle
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/config/TelemetryConfig.java
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/TelemetryEventListener.java
- echo-telemetry/src/test/groovy/com/netflix/spinnaker/echo/telemetry/TelemetryEventListenerSpec.groovy
Fixes https://github.com/spinnaker/spinnaker/issues/4885
I tried (a lot) to make this broader - to change [Event.content](https://github.com/spinnaker/echo/blob/master/echo-model/src/main/java/com/netflix/spinnaker/echo/model/Event.java#L28) from a `Map` to a proper POJO `Content` object - but I couldn't get Jackson deserialization to work as expected and _not_ have to change large amounts of both prod and test code (access like `event.content.something.somethingElse` is pervasive across this codebase).
So instead I opted to fix it locally - grabbing the Map and converting it locally to known fields and setting reasonable defaults for those fields, should they be absent.
One thing to note also is the wrapper `TEL` object - because there are a lot of duplicate names here, I wrapped the …
> fix(stats): Parse Event objects into structured POJOs for Telemetry events

- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/TelemetryEventListener.java
- echo-telemetry/src/test/groovy/com/netflix/spinnaker/echo/telemetry/TelemetryEventListenerSpec.groovy
This adds the application ID (which is an autogenerated-but-editable-by-the-user ULID) as a salt for application IDs.
The [original design doc](https://docs.google.com/document/d/12_YcUnbE63vshofo9krQlMRiqW2WMjSYGCjb4G6dOb8/edit?ts=5d4dc2e8#) called for using the application creation time, but was pointed out that not all operations have this value, and that it doesn't really contain all that many bits of entropy. Using the instance ULID should solve both issues. Because the instance ID was actually being sent over the wire during an event, I changed to hash it as well.
Fixes https://github.com/spinnaker/spinnaker/issues/4863
> feat(stats): Adds salt to application ID hash

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ManualEventHandler.java
This pull request removes confusing/unnecessary error log from `ManualEventHandler#resolveArtifacts`.
ref: [feat(artifacts): populate artifacts for manual trigger](https://github.com/spinnaker/echo/pull/509)
The error log was added in the commit:
https://github.com/spinnaker/echo/pull/509/commits/1a6fb33f56235019d4987fda777908173f50fa32#diff-3861ae251662b1f07aee9125cec36ad4R129
But the code was changed in the next commit in the pull request for existing behavior:
https://github.com/spinnaker/echo/pull/509/commits/8c371ce2f7e81f9ed14eb0baf5d67b366d6fcb7a#diff-3861ae251662b1f07aee9125cec36ad4R143
So the error log is unnecessary and confusing.
Actually I was confused with the error log while debugging 😁
> fix(triggers): Remove confusing/unnecessary error log

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgentSpec.groovy
This fixes an issue where Echo would send failure notifications for cancelled stages, and tries to account for a similar scenario with cancelled pipelines where the execution object has two different fields for cancellation status and only one was being checked.
Also added tests to cover some of the basic flows in `AbstractEventNotificationAgent`, which is where this logic resides.
> fix(notifications): Don't send failure notifications for cancelled pipelines and stages

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/BearychatNotificationAgent.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/GoogleChatNotificationAgent.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgent.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/TwilioNotificationAgent.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgentSpec.groovy
Right now we can't send notifications for tasks. Why? Not sure. This code is 2015 vintage.  
This PR adds support for sending notifications for tasks:
```json
"trigger": {
"notifications": [
{
"address": "#myslackchannel",
"level": "pipeline",
"type": "slack",
"when": [
"orchestration.starting",
"orchestration.complete",
"orchestration.failed"
]
}
]
},
```
It also moves some error handling from subclasses to the parent class because of 💁style.
> feat(tasks): allow notifications for tasks

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
Closes:
-  https://github.com/spinnaker/spinnaker/issues/4955
- https://github.com/spinnaker/spinnaker/issues/4982
When manually re-running an execution, Deck hydrates the manual trigger it creates with properties from the [execution trigger](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx#L291) of the execution being re-run. However, the execution trigger was missing the `registry` field, so Deck was creating an [incomplete reference](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/docker/src/pipeline/trigger/DockerTriggerTemplate.tsx#L70). This was only a problem with re-runs, and not normal manual executions, because in a normal manual execution we build a manual trigger based on the …
> fix(triggers): add missing docker properties to trigger model

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/SlackConfig.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/config/SlackConfigSpec.groovy
Allow slack notifications to be sent to compatible implementations.
spinnaker/spinnaker#4634
> feat(slack): Make slack base url configurable

- .mergify.yml
Reverts spinnaker/echo#673
I'm fairly certain this turns every reviewer into an approver. (Reviewers have the `triage` permission, which allows them to [add labels](https://help.github.com/en/articles/repository-permission-levels-for-an-organization).)
Merging this without a review, since you did too :wink:
> chore(github): revert mergify config

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Trigger.java
- echo-model/src/main/java/com/netflix/spinnaker/echo/model/trigger/GitEvent.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/GitEventHandler.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/GitEventHandlerSpec.groovy
- echo-test/src/main/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/BitbucketWehbookEventHandler.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/GithubWebhookEventHandler.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/GitlabWehbookEventHandler.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/StashWebhookEventHandler.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/github/GithubPullRequestEvent.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/github/GithubPushEvent.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/github/GithubWebhookEvent.java
- echo-webhooks/src/test/groovy/com/netflix/spinnaker/echo/controllers/WebhooksControllerSpec.groovy
When dealing with webhook git triggers the event of the webhook does not reach the pipeline contexts. This PR makes this event available in the contexts of the pipeline execution.
This should no affect the current conditional for matching pipelines (source, project, slug, branch), it is just informative like the hash field.
For example: allowing only github events where someone open/close a pull request using check preconditions, or if there is github push event follow a different branch in the pipeline, instead of one for pull request events.
For bitbucket server I used the header [ X-Event-Key ](https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html)
For bitbucket cloud I used the header [X-Event-Key](https://confluence.atlassian.com/bitbucket/event-payloads-740262 …
> feat(triggers): add action field to git triggers context

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BuildEventHandler.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BuildEventHandlerSpec.groovy
Implements [Spinnaker Issue #5053](https://github.com/spinnaker/spinnaker/issues/5053)
Use case is conditionally triggering pipelines after a successful Jenkins build.  For example, Jenkins may be setup for builds on all branches but Spinnaker pipelines should only be master.  More complex use cases are possible too, like triggering 'stage' pipelines on feature/* branches or when a Jenkins build has something like `deploy_target=stage`.
* Adds support for payloadConstrains: {} dictionary for Build triggers (e.g. Jenkins).  
* If payloadConstraints are present, then properties in the properties file must pass the constraints to trigger a build
* Regexp is supported (works the same as webhook and pub/sub payloadConstraints)
* Does not support Manual Pipeline triggers (ie: if build 30 fails …
> feat(triggers) Adds support for payloadConstraints on property files for build triggers

- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/TelemetryEventListener.java
- echo-telemetry/src/test/groovy/com/netflix/spinnaker/echo/telemetry/TelemetryEventListenerSpec.groovy
- echo-web/config/echo.yml
- echo-web/src/test/java/com/netflix/spinnaker/echo/telemetry/TelemetrySpec.java
- echo-web/src/test/resources/echo-test.yml
Back in October, the telemetry endpoint went down, causing our nightly tests to start failing. The root cause was that the resiliance4j circuit breaker library was hooked up to the Spring Boot health endpoint, so when the breaker was tripped (yay that this part worked as intended), it caused Echo's `/health` endpoint to start returning 503s, and thus traffic to it was halted in a Kubernetes environment.
The fix is to not register the circuit breaker with the health endpoint. I added a system test to confirm this (heavy handed, yes, but I don't know how else to test this dependency) and for good measure, I added a unit test that throws various Retrofit errors.
tag: https://github.com/spinnaker/spinnaker/issues/5144
> fix(stats): Deregister the telemetry circuit breaker from the health indicator

- echo-api/echo-api.gradle
- echo-api/src/main/java/com/netflix/spinnaker/echo/extension/rest/RestEventParser.java
- echo-rest/echo-rest.gradle
- echo-rest/src/main/groovy/com/netflix/spinnaker/echo/config/RestConfig.groovy
- echo-rest/src/main/groovy/com/netflix/spinnaker/echo/events/RestEventListener.groovy
- echo-rest/src/test/groovy/com/netflix/spinnaker/echo/events/RestEventListenerSpec.groovy
- settings.gradle
Alpha PF4J extension for parsing Echo events prior to POST to configured service.  This implementation is quite simple at the moment.
Current implementation will override any additional configuration (like `wrap`).  However, as this progresses I would like to see this extension point work with existing configurations and allow multiple parsers for multiple configured URLs.
If things progress well, the more powerful extension point would be `EchoEventListener` which would allow us to decompose echo event listeners into discrete plugins.
> feat(extension): Add event parser extension for echo-rest

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
This is needed for https://github.com/spinnaker/orca/pull/3286, so that users can opt-into the new spelEvaluator version
> fix(models): add spelEvaluator field to pipeline

- echo-pubsub-google/echo-pubsub-google.gradle
Use a pubsub client lib that includes a fix for the thread leakage issue (spinnaker/spinnaker#4835, see also https://github.com/googleapis/java-pubsub/commit/7f26f7aef1416e240ff49d59e58c846efba12924).
> fix(dependencies) Fix #4835 by using a pubsub library that includes a fix

- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ManualEventHandlerSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/PubsubEventHandlerSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/WebhookEventHandlerSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ExpectedArtifactExpressionEvaluationPostProcessorSpec.groovy
The all-arg and no-arg constructors for Artifact were deprecated in spinnaker/kork#429. Replace their usages with a builder.
> refactor(artifacts): Use builder to create artifacts

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
follow up from https://github.com/spinnaker/orca/pull/3335
plumb through the `templateVariables` for triggering to work on mptv2 pipelines that use spel v4
> fix(mpt): include templateVariables in pipeline model

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/GithubConfig.java
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/config/GithubConfigSpec.groovy
I restore the endpoint in the Github configuration. If it doesn't receive any value, the default value that already exists will remain.
> fix(github): Put back github endpoint configuration

- echo-core/src/main/java/com/netflix/spinnaker/echo/services/Front50Service.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java
The only call from echo to the front50 /pipelines/id/history endpoint passes limit=1. Replace it with the new endpoint /pipelines/id/get that gets the current state of the pipeline config and does so more performantly than the history endpoint.
Requires front50 >= 2.11.0, which is when this new endpoint was added.
> perf(pipelines): Use new endpoint to fetch pipeline config

- echo-core/src/main/java/com/netflix/spinnaker/echo/config/EchoCoreConfig.java
References PlatformComponents before DiscoveryPollingConfiguration to resolve
ConditionalOnBean and ConditionalOnMissingBean not finding DiscoveryClient
> fix(discovery): make spring config order explicit to fix Conditional bean loading

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/SlackConfig.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackClient.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/config/SlackConfigSpec.groovy
In a previous PR we addressed spinnaker/spinnaker#4634 by allowing to specify the baseURL for slack. Unfortunately we're always posting to BASE_URL/services/TOKEN because of the way the client is declared.
With this patch I move the /services part to the base url and we append the token to the end of the url, this way the user can provide the full url to their webhook endpoint.
E.g: https://example.com/webhooks, we'll send a post request for https://example.com/webhooks/${token} instead of https://example.com/webhooks/services/${token} as we would currently do.
> fix(slack): Allow specifying full url for webhooks integration

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/TelemetryEventListener.java
Part of https://github.com/spinnaker/spinnaker/issues/5302
Goes in tandem with https://github.com/spinnaker/orca/pull/3360
This PR detects if a pipeline was sourced from a Managed Pipeline Template (either V1 or V2) and sets the Execution.Type to match.
> fix(stats): MPT tracking

- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/TelemetryEventListener.java
- echo-telemetry/src/test/groovy/com/netflix/spinnaker/echo/telemetry/TelemetryEventListenerSpec.groovy
It seems the explicitly set `source=null` comes across the wire to Echo often enough that it halted all testing stats for the past few days. Had `source` been not set the default object would be fine.
This will need to be cherry picked into 1.18
> fix(stats): Fix NPE when pipeline explicitly sends 'source=null'

- README.md
* Remove newline in the list of Orca's description
* No need
> Remove newline in Orca notification description

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgent.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackAppService.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackInteractiveNotificationService.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackNotificationService.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/slack/SlackInteractiveNotificationServiceSpec.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/slack/SlackServiceSpec.groovy
Fixes the following:
1. Fix and enable signature verification for Slack callbacks: turns out Spring was messing with the URL-encoded payload for some reason (or so it seems -- at least I couldn't find any other culprits on the path of the request processing). I was unable to find a matching issue against Spring although there were other problems reported with inconsistent URL encoding behavior.
2. Left-over refactored method call that I missed to update before.
> fix(slack): Left-over fixes from interactive notifications

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/controller/NotificationController.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/NotificationControllerSpec.groovy
I assumed the logical `&&` would short-circuit the rest of the expression, but obviously not. Reading the [groovy docs](https://docs.groovy-lang.org/latest/html/documentation/core-operators.html#_logical_operators), I would expect it to work, but clearly it doesn't.
I added a test where an interactive notification handler is registered before a non-interactive one, which was the situation we had in our deployment and the reason you see this line in the stack trace in the log, which was the hint that led me to finding the bug:
```
at com.netflix.spinnaker.echo.slack.SlackInteractiveNotificationService.handle(SlackInteractiveNotificationService.groovy)
```
The second hint was that the error we experienced was when trying to send a PagerDuty notification, which should obviously not be …
> fix(notifications): Fix precedence of notification handlers in controller

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/PipelineTriggerConfiguration.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/QuietPeriodIndicatorConfigurationProperties.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/QuietPeriodController.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/QuietPeriodIndicator.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/QuietPeriodIndicatorSpec.groovy
This change allows setting of the quiet period via spring config or a dynamic config service (without redeploy of the service).
The properties are:
- `quiet-period.start-iso`: start time
- `quiet-period.end-iso`: end time
- `quiet-period.enabled`: global enable/disable flag
Can be set in yml, like so:
```yaml
quietPeriod:
enabled: true
startIso: 2020-01-01T21:00:00Z
endTime: 2020-01-02T21:00:00Z
suppressedTriggerTypes:
- cron
- docker
- git
- jenkins
```
note that `suppressedTriggerTypes` can't be set via a dynamic property. Not sure if there is a need for this, so leaving it out for now for simplicity.
This change also adds:
* more verbose logging as to why a pipeline is or is not triggered during the quiet period
* a `GET: /quietPeriod` endpoint that returns the current quiet period …
> fix(quietperiod): Allow the quiet period to be set by a dynamic service

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/controller/NotificationController.groovy
Fixes a bug in the logical condition to select the correct notification service based on whether the notification is interactive or not and the service supports it.
> fix(notifications): Fix selection of interactive vs. non-interactive handler

- echo-pubsub-aws/echo-pubsub-aws.gradle
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriber.java
- gradle.properties
This is for consistency with the other spin services. Mainly so that plugins can be written the same way across services. It would be nice to keep kork versions consistent for a release.
> chore(dependencies): update korkVersion

- echo-core/src/main/java/com/netflix/spinnaker/echo/discovery/DiscoveryActivated.java
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriberProvider.java
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubPublisher.java
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/TriggerConverter.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/TriggerConverterSpec.groovy
Triggers support a parameters map, but for cron triggers it gets lost along the way and never makes it to orca, meaning that only default parameter values can be used for cron triggers.
To work around this, users have been duplicating pipelines with different default values and different triggers. This does not scale for obvious reasons and is just generally cumbersome.
> Parameters in cron triggers

- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/config/TelemetryConfig.java
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/TelemetryEventListener.java
This is the core of this request in https://github.com/spinnaker/halyard/pull/1565#discussion_r390586727
The rest of the change involves renaming the whole module and a whole lot of `s/telemetry/stats/g` changes - I'd like to confirm that this minimal, understandable change actually works as expected and then we can rename the module in a separate cleanup PR.
> chore(stats): Rename Spring config props from telemetry to stats

- echo-notifications/echo-notifications.gradle
Upgrade org.jsoup version.
Fix [CVE-2015-6748](https://nvd.nist.gov/vuln/detail/CVE-2015-6748) caused by org.jsoup.
> chore(vulnerabilities): bump jsoup version resolve CVE-2015-6748

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/IgorConfig.java
- echo-web/src/main/java/com/netflix/spinnaker/echo/config/Front50Config.java
This fixes [spinnaker/issues/5035](https://github.com/spinnaker/spinnaker/issues/5035) and [spinnaker/issues/4941](https://github.com/spinnaker/spinnaker/issues/4941)
This fix adds SpinnakerRequestInterceptor to Front50 OkHttpClient in Echo. 
Currently, Front50 OkHttpClient in Echo does not propagate the AuthenticationRequest [Headers](https://github.com/spinnaker/kork/blob/v7.5.1/kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java#L39) to Front50 on Http calls. Reason for this behaviour is due to Front50 Client created without SpinnakerRequestInterceptor. This interceptor ensures Headers are propagated as part of request headers on Http calls.
This has caused Echo not able to get the latest pipeline configuration from Front50 and rely on Pipeline …
> fix(front50): Add SpinnakerRequestInterceptor to Front50 OkHttpClient

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/api/Notification.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/bearychat/BearychatNotificationService.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/email/EmailNotificationService.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/googlechat/GoogleChatNotificationService.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/jira/JiraNotificationService.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/InteractiveNotificationCallbackHandler.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/NotificationService.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/NotificationTemplateEngine.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/pagerduty/PagerDutyNotificationService.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackNotificationService.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/twilio/TwilioNotificationService.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/ManualJudgmentTemplateTest.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/NotificationControllerSpec.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/NotificationTemplateEngineSpec.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/slack/SlackInteractiveNotificationServiceSpec.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/slack/SlackNotificationServiceSpec.groovy
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubNotificationEventListener.java
This takes the Notification.Type enum and makes it a simple String. This makes it possible to create a NotificationListener extension point and plugins can add their own notification types once this is no longer a closed enum. I'm not a fan of Strings, and first tried to keep this typed using extendable enums. Basically turning Notification.Type into an interface that the enums and other enums/classes could use. This got weird with classpath issues (using equals on type with the plugins), and JSON deserialization on type. I experimented with a custom deserializer for notification type and that could work, but ultimately Notification will probably end up in echo-plugins-api and the deserializer will have to live there too and that adds Jackson deps to echo-plugins-api.
Then when it got …
> fix(notifications): remove notification type enum

- .github/workflows/build.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- Dockerfile.compile
- gradle.properties
We don't actually need `-PenableCrossCompilerPlugin=true` in `build.yml` or `release.yml` (it's turned on already by the Nebula plugin since we're making a candidate build) but I thought it was worth adding for clarity.
For the GitHub workflows, I didn't know a great way to test it, so I first read setup-java to determine how the `$PATH` manipulation works, then I tested it with `pr.yml` by:
1. Pushing some code to this PR that uses a Java 11 API (`Optional#stream()`) and seeing the build fail (proving we're compiling against the Java 8 APIs)
2. Changing it to `-PenableCrossCompilerPlugin=false` and watching the build succeed (proving we're using the Java 11 `javac`)
> chore(java11): Compile with Java 11 (but targeting Java 8)

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BaseTriggerEventHandler.java
Make BaseTriggerEventHandler's constructor public so we can extend the
class outside of the package. This makes it easier for the community to
add in customized trigger event handle.
@ezimanyi
> refactor(triggers): make BaseTriggerEventHandler's constructor public

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/OrcaExecutionStatus.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/OrcaService.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/OrcaTaskExecutionStatus.java
Add execution status as part of orca service pipeline response. 
Here is the response in Orca: https://github.com/spinnaker/orca/blob/94423342e309ed3c545c9b312fd0d7597f8bbf76/orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/models/PipelineExecution.java#L89
Here is the ExecutionStatus in Orca:
https://github.com/spinnaker/orca/blob/94423342e309ed3c545c9b312fd0d7597f8bbf76/orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/models/ExecutionStatus.java
The execution status of a pipeline can be used by event handlers to determine what to do.
@robzienert
> feat(triggers): add execution status as part of orca service pipeline response

- echo-api/echo-api.gradle
- echo-api/src/main/java/com/netflix/spinnaker/echo/api/events/Metadata.java
- echo-api/src/test/kotlin/com/netflix/spinnaker/echo/api/events/MetadataTest.kt
In https://github.com/spinnaker/echo/pull/790 I removed `HttpHeaders` so that `echo-api` could be dependency free (basically, just Java) -- this is important for the ongoing extensibility / plugin work we are doing.
However, I overlooked that `HttpHeaders` builds a case insensitive map.  This resolves that issue.
Resolves: https://github.com/spinnaker/spinnaker/issues/5645
Relates to: https://github.com/spinnaker/echo/pull/840
> fix(headers): Metadata requestHeaders lookup should be case insensitive

- Dockerfile.compile
This failed last night and failed for me locally: https://console.cloud.google.com/cloud-build/builds/0edd57a0-c6cb-4227-8754-fff7bcab134d;tab=detail?organizationId=433637338589&project=spinnaker-community
Copied this from https://github.com/spinnaker/clouddriver/blob/master/Dockerfile.compile#L8 (but path is changed for alpine)
> fix(builds): Add JDK_18 env var for failing Docker nightly builds

- echo-web/config/echo.yml
- halconfig/echo-scheduler.yml
* fix(config): remove unnecessary config properties 
Timezone is already defaulted in the base config, and thread pool size is never read.
* feat(config): add worker and scheduler profiles 
Add profiles for sharded Echo, which will be referenced in the base Kustomization available as part of the Kleat deployment workflow.
> feat(config): add worker and scheduler profiles

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/pubsub/MessageDescription.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/TwilioConfig.groovy
- echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/PubsubMessageHandler.java
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/config/GooglePubsubProperties.java
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GooglePubsubSubscriber.java
* fix(echo): Add default twilio API endpoint
Currently halyard is explicitly setting this default; instead of having kleat need to know about this, just have it defaulted in echo if kleat doesn't pass anything along. (This won't break any existing config as Halyard is always passing this, so we'll never fall to the default, and if anyone is overriding it that will still be respected.)
* refactor(pubsub): Minor pubsub code cleanup
While reading through this code to document the config for kleat, I made a few changes to improve it:
* As I traced everywhere we pass ackDeadlineSeconds, I changed it from a NonNull Integer to an int
* Added an explicit type on a map to fix a compiler warning
> fix(echo): Add default twilio API endpoint

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/EmailNotificationAgent.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/EmailNotificationAgentSpec.groovy
The change enables use of pipeline parameters in address/cc fields of email notifications - can be either:
"notifications": [
{
"address": "${parameters.Email}",
"level": "stage",
"message": {
...
or a longer form:
"notifications": [
{
"address": "${execution.trigger.parameters.Email}",
"level": "stage",
"message": {
...
> fix: enable use of pipeline parameter in the email address field (#5697)

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/GitEventHandler.java
As discussed in https://github.com/spinnaker/echo/pull/865 
Lower casing the github webhook secret header key for the lookup solves this specific issue.
For the record, metadata requestHeaders lookup is still case sensitive, and I am not solving that in this PR.
> fix(headers): Lowercase X-Hub-Signature for a successful lookup

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/QuietPeriodIndicatorConfigurationProperties.java
My change in https://github.com/spinnaker/echo/pull/784 caused issues for anyone who had the quiet period properties set as I removed the setters
This change fixes that
> fix(quietperiod): Fixup config props

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/DryRunConfig.java
- Failing to inject bean of type `OkHttpClient`.
- Moving to the new client provider implementation instead.
> fix(misc): Move to the client provider to build retrofit client

- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ManualEventHandlerSpec.groovy
The kork bump changes some non-specified fields in Artifact from null to empty string, which breaks this test. Fix it to not care.
> fix(test): Fix over-specified test

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/EmailNotificationAgent.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/EmailNotificationAgentSpec.groovy
Reverts spinnaker/echo#869
This change did not properly address the underlying issue which was in `orca` (https://github.com/spinnaker/orca/pull/3712). Furthermore, this change in `echo` introduced a regression in the `RestListener` which prevented it from actually sending any events if there was an email notification also present on the stage/pipeline
> Revert "fix: enable use of pipeline parameter in the email address field (#5697)"

- echo-rest/src/main/java/com/netflix/spinnaker/echo/config/RestProperties.java
- echo-rest/src/main/java/com/netflix/spinnaker/echo/events/RestEventListener.java
- echo-rest/src/test/groovy/com/netflix/spinnaker/echo/events/RestEventListenerSpec.groovy
Add configurable retries (default to non-behavior changing 1) to sending events to a REST listener
> feat(rest): add retries to sending rest events

- README.md
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/monitor/TriggerMonitor.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiatorSpec.groovy
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/MissedPipelineTriggerCompensationJob.groovy
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineTriggerJob.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/MissedPipelineTriggerCompensationJobSpec.groovy
Adds two dynamic properties:
* `scheduler.suppressTriggers`, and
* `scheduler.compensationJob.suppressTriggers`
(both default to `false`)
This is useful when there are two `echo` clusters (for redundancy) to process events but only one of them should actually trigger.
Processing triggers (e.g. running the schedule) but triggering on only one of the clusters allows both clusters to be "in-sync" and when a switch is needed there will be no (or very few) double triggers.
> feat(triggers): Add ability to suppress triggers at runtime

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiatorSpec.groovy
Fixup for my prior PR, #927.
I don't want the props to need the `enabled` suffix, hence changing `isEnabled` -> `getConfig` for the dynamicConfig query
> fix(trigger): Fixup property names for trigger suppression

- README.md
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiatorSpec.groovy
Changing to "positive" by default instead of "negative" property to align with similar properties in `igor`, and, e.g. `orca.enabled`
> fix(triggers): Changing format for suppression properties

- echo-web/echo-web.gradle
This protects us from the scenario wherein the Implementation-Version set for a test actually ends up being the version used in a final JAR artifact (since Gradle does not re-compile the JAR after it has been compiled for a test task).
> fix(build): Do not set Implementation-Version in test JAR if already set to a valid version

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgent.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackNotificationService.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/slack/SlackNotificationServiceSpec.groovy
This PR is to fix spinnaker/spinnaker#5841.
Slack API for sending notification supports channel name, channel name with `#` prefix and channel ID as its address. These 3 options can be used interchangeably.
Echo's Slack notification service doesn't support putting channel ID in the address field.
Before this PR, SlackNotificationService prefix the channel address with `#` if it's missing. If the channel ID is input by the user, it won't work properly with the `#` prefix.
After this PR, Slack notification service keep channel address as is. Users are allowed to specify channel ID.
> fix(notification): Support channel ID as Slack notification address

- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/PipelineCountsDataProvider.kt
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/SpinnakerEnvironmentDataProvider.kt
- echo-telemetry/src/test/kotlin/com/netflix/spinnaker/echo/telemetry/PipelineCountsDataProviderTest.kt
* whether or not Spinnaker is running under Kubernetes
* which artifacts were used to deploy Spinnaker
* the number of pipelines in this Spinnaker instance
* the number of pipelines in the event's application
See spinnaker/kork#692
> feat(stats): add support for new stats

- echo-telemetry/echo-telemetry.gradle
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/InstanceIdSupplier.kt
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/SpinnakerInstanceDataProvider.kt
- echo-telemetry/src/test/kotlin/com/netflix/spinnaker/echo/telemetry/InstanceIdSupplierTest.kt
- echo-telemetry/src/test/kotlin/com/netflix/spinnaker/echo/telemetry/SpinnakerInstanceDataProviderTest.kt
Currently the only place that the unique id for a Spinnaker instance is persisted is in the hal config. This works for users using halyard as it gets generated the first time it is needed then gets re-used on subsequent deployments. (It does have the failure mode of copying the hal config as then the new instance would have the same id as the old one.)
This doesn't work for users either deploying without Halyard or deploying via kleat. In this case there is nowhere to store this uniqueid (as kleat explicitly treats the config only as input).
To solve this problem, we'll store the unique id in redis. On startup, we'll check to see if there's a value in redis; if there is we'll use that, if not we'll use the configured value (and persist it).
> feat(stats): Persist the unique id to redis

- .github/PULL_REQUEST_TEMPLATE.md
The link to the page explaining how to submit a patch was broken.
> fix(docs): Updates broken link

- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/config/TelemetryConfig.kt
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/ExecutionDataProvider.kt
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/InstanceIdSupplier.kt
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/PipelineCountsDataProvider.kt
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/SpinnakerEnvironmentDataProvider.kt
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/SpinnakerInstanceDataProvider.kt
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/TelemetryEventListener.java
The rollout plan for stats involved having the stats become opt-out (ie enabled by default) as of Spinnaker 1.19. While this was implemented, it was only done at the Halyard level; Halyard now explicitly sends 'stats.enabled = true' by default (and sends 'stats.enabled = false' for users who have disabled stats collection).
This is confusing, as stats collection is now opt-out for Halyard users but still opt-in for anyone writing their own config. As part of the effort to have services own and default their own config, update echo to be consistent with Halyard (and with the intent of the rollout plan).
With this change, echo will send usage statistics for anyone who does not have a 'stats.enabled' field in their config. Halyard users should all have this field already set to either …
> feat(stats): Enable stats by default in echo

- echo-api/src/main/java/com/netflix/spinnaker/echo/api/events/NotificationAgent.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/ExtensionNotificationAgent.java
- echo-plugins-test/src/main/kotlin/com/netflix/spinnaker/echo/plugins/NotificationAgentExtension.kt
- echo-plugins-test/src/test/kotlin/com/netflix/spinnaker/echo/plugins/test/EchoPluginsFixture.kt
- echo-plugins-test/src/test/kotlin/com/netflix/spinnaker/echo/plugins/test/EchoPluginsTest.kt
- echo-web/echo-web.gradle
- echo-web/src/main/java/com/netflix/spinnaker/echo/config/EchoCoreConfig.java
Adds NotificationAgent extension point.
> feat(notifications): add NotificationAgent extension point

- echo-api/src/main/java/com/netflix/spinnaker/echo/api/events/NotificationAgent.java
Allows a notification agent plugin to define a custom UI rather than using the autogenerated UI (e.g., if there's some custom validation logic that's needed for inputs).
See: https://github.com/spinnaker/deck/pull/8432
> feat(notifications): add switch for supplying custom notification UI

- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/InvalidCronExpressionException.java
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineConfigPollingMetrics.java
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineConfigsPollingJob.groovy
- echo-scheduler/src/test/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/PipelineConfigsPollingJobSpec.groovy
We want to know when `echo` fails to register a trigger with quartz but only if it's not a user error (e.g. bad cron express, cron expression in the past, etc).
Quartz, unfortunately, often throws a non-descript `SchedulerException` which doesn't provide machine identifiable way to decipher if this is a user error or a system error.
This change replicates some logic that's in [quartz](https://github.com/quartz-scheduler/quartz/blob/939a9a25fbf3b374608de59e413405aebe10c089/quartz-core/src/main/java/org/quartz/core/QuartzScheduler.java#L882-L896)
to decide if the trigger is valid, if not we will log a warning, but won't increment any failure metrics.
If the are exceptions/errors outside of the trigger validation path, those will still log errors and increment failure metrics
> fix(trigger): handle quartz errors better

- echo-api-tck/README.md
- echo-api-tck/echo-api-tck.gradle
- echo-api-tck/src/main/kotlin/com/netflix/spinnaker/echo/api/test/EchoFixture.kt
- echo-api-tck/src/main/resources/echo-test-app.yml
- echo-api-tck/src/test/kotlin/com/netflix/spinnaker/echo/api/test/EchoFixtureTest.kt
- settings.gradle
This is modeled after https://github.com/spinnaker/orca/tree/master/orca-api-tck and has the same purpose (letting plugin developers write integration tests). Planning on doing this for quite a few other services. There isn't much here, but it can be tough for plugin developers to know exactly what config values they need to get Echo to run in a test environment.
> feat(test): add echo integration test fixture

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/api/Notification.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackNotificationService.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/slack/SlackNotificationServiceSpec.groovy
A flag (defaulting to false) to use the new slack bot even if you have no interactive actions.
This defaults to the old behavior if you don't specify the flag in your notification payload.
This PR also adds support for the subject line of a slack message. Previously we were using "Spinnaker Notification" which is both redundant (because of the name of the bot) and not useful (because we are sending a subject in the slack notification). 
This shows previous (default subject) and new (a subject that I sent)
> feat(slack): flag to use interactive bot

- echo-core/src/main/java/com/netflix/spinnaker/echo/events/EventPropagator.java
- echo-core/src/main/java/com/netflix/spinnaker/echo/notification/ExtensionNotificationAgent.java
- echo-core/src/test/groovy/com/netflix/spinnaker/echo/events/EventPropagationSpec.groovy
- echo-plugins-test/src/test/kotlin/com/netflix/spinnaker/echo/plugins/test/EchoPluginsFixture.kt
- echo-plugins-test/src/test/kotlin/com/netflix/spinnaker/echo/plugins/test/EchoPluginsTest.kt
- echo-web/src/main/java/com/netflix/spinnaker/echo/config/EchoCoreConfig.java
- gradle.properties
- Moved `ExtensionNotificationAgent` to `echo-core`
- Refactored `EventPropagator` to use `ObjectProvider` for `EventListener` beans
- Fixed test for V2 plugin support
> refactor(core): Support plugins v2 framework

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/slack/SlackInteractiveNotificationService.groovy
I tried overriding the log level config for this class via Spring's `logging.level` config, but it didn't work for some reason, so bumping the level in code.
> chore(logs): Bump log level for Slack interactive callbacks

- echo-core/src/main/java/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.java
Was missed on the original Groovy -> Java refactor.
> fix(core): Add closing '}' on `@Value`

- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriber.java
- echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriberProvider.java
Follow up to https://github.com/spinnaker/echo/pull/903
The "problem" with that PR was that the flag used for `isEnabled` (`pubsub.amazon.enabled`) was also the same flag that gated bean creation
for the pubsub components, e.g. [here](https://github.com/spinnaker/echo/blob/master/echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/config/AmazonPubsubConfig.java#L28)
This meant that if a server group comes up with `pubsub.amazon` OFF it can never be turned ON on the fly without restarting those instances.
This change, divorces the two concepts into "pubsub enabled" and "pubsub processing enabled" with a new flag `pubsub.amazon.processing.enabled`
Additionally, if processing is turned off we will busy spin, adding a `sleep` to alleviate that
> fix(pubsub): Add ability to control pubsub message processing

- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/config/SchedulerConfiguration.groovy
Noticed that some triggers got wedged in the `ACQUIRED` state. Following the suggestion from http://www.quartz-scheduler.org/documentation/2.3.1-SNAPSHOT/faq.html
Setting `org.quartz.jobStore.dontSetAutoCommitFalse=false`
> fix(quartz): set org.quartz.jobStore.dontSetAutoCommitFalse

- build.gradle
- echo-core/src/main/java/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiator.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCacheSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/orca/PipelineInitiatorSpec.groovy
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/config/SchedulerConfiguration.groovy
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/scheduler/actions/pipeline/QuartzDiscoveryActivator.java
Add discovery status check for triggering, polling pipelines configs, and pausing/resuming quartz based on discovery status
> fix(discovery): Respect discovery status

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCacheSpec.groovy
Follow up to https://github.com/spinnaker/echo/pull/1050
Apparently, being `UP` is predicated on the config poller having successfully run. But now that I made configpoller predicated on being `UP` echo doesn't come up...
There is no harm (just wasted RPS) for disabled instances getting config, so I am undoing this part of the change.
Just leaving the discovery activated part for scheduler
I didn't catch this because I tested with discovery being OFF and then turning it OFF and not the other way around.
> fix(discovery): Undo respecting discovery for config poller

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/PipelineTriggerConfiguration.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/PubsubEventHandler.java
A while ago I added the ability to override the pubsub event handler because I was doing custom stuff. I'm removing this capability because the way we ended up implementing things means its fine for the handlers to run side by side.
Also making a small change to the pubsub handler to read the list of supported trigger types from the already defined function.
> chore(pubsub): don't allow overriding of bean

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/JiraConfig.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/jira/JiraNotificationService.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/jira/JiraService.java
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/jira/JiraNotificationServiceSpec.groovy
`transitionContext` payload can be the full Jira transition REST API payload, however the transition ID will be looked up based on the transition name
> feat(jira): Add Jira issue transition to JiraNotificationService

- echo-pipelinetriggers/echo-pipelinetriggers.gradle
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/artifacts/ArtifactMatcher.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/WebhookEventHandler.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/artifacts/ArtifactMatcherSpec.groovy
- gradle.properties
This changes is about support [JsonPath](https://github.com/json-path/JsonPath) expressions in the payload constraints for Webhook triggers.
The initial issue opened for request this is here: https://github.com/spinnaker/spinnaker/issues/3643
This feature enable users to include a JsonPath expression in the key of a payload constraint, so it first check if the key is present in first level json key (as it currently works). If the key is not present in the first level json, it will try to search the value in the payload using the key as a jsonpath expression then if exists it try to match with the regex provided.
Payload Constraint examples:
**Key** | **Value**  
foo   :   bar
foo   :   *ar
$.foo.bar  :  *ar
The json expression must be a valid jsonpath expression and it must point to a …
> feat(constraint): support jsonpath expression in payload constraint key

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/MicrosoftTeamsConfig.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/microsoftteams/MicrosoftTeamsNotificationService.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/microsoftteams/MicrosoftTeamsService.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/MicrosoftTeamsNotificationAgent.java
- gradle.properties
This PR adds support for new webhook URLs for Microsoft Teams notifications.
See issue https://github.com/spinnaker/spinnaker/issues/6324 for more details.
> fix(notifications): Support new Microsoft Teams webhook URLs

- echo-telemetry/echo-telemetry.gradle
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/PipelineCountsDataProvider.kt
to clean up warnings like:
```
2021-03-17 22:51:04.801  WARN 1 --- [oScheduler-1063] c.n.s.okhttp.OkHttp3MetricsInterceptor   : Request GET:http://spin-front50.spinnaker-stage:8080/pipelines?restricted=false is missing [X-SPINNAKER-USER, X-SPINNAKER-ACCOUNTS] authentication headers and will be treated as anonymous.
Request from: com.netflix.spinnaker.okhttp.MetricsInterceptor.doIntercept(MetricsInterceptor.java:98)
at com.netflix.spinnaker.okhttp.OkHttp3MetricsInterceptor.intercept(OkHttp3MetricsInterceptor.java:36)
at com.netflix.spinnaker.echo.telemetry.PipelineCountsDataProvider.retrievePipelines(PipelineCountsDataProvider.kt:48)
at com.netflix.spinnaker.echo.telemetry.PipelineCountsDataProvider.access$retrievePipelines(PipelineCountsDataProvider.kt:30)
at …
```
> chore(logs): allow anonymous call to front50 to get pipelines

- echo-core/src/main/java/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.java
This change updates the logging so that when a notification agent fails the exception is logged.
> fix(notification): log exception on failure

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/Pipeline.java
- echo-model/src/test/groovy/com/netflix/spinnaker/echo/model/PipelineSpec.groovy
It adds support for max concurrent pipeline executions. If concurrent pipeline execution is enabled, pipelines will queue when the max concurrent pipeline executions is reached. Any queued pipelines will be allowed to run once the number of running pipeline executions drops below the max. If the max is set to 0, then pipelines will not queue.
This is the proposed change for spinnaker/spinnaker#6558.
Changes to orca, front50 and deck are also needed in order to expose max concurrent pipeline executions as a pipeline configuration to Spinnaker users.
(Orca pull request: spinnaker/orca#4193)
(Front50 pull request: https://github.com/spinnaker/front50/pull/1080)
(Deck pull request: https://github.com/spinnaker/deck/pull/9777)
> feat(pipeline executions/echo): Add support for max concurrent pipeline executions

- echo-webhooks/echo-webhooks.gradle
Below errors that appear when upgrading  spring boot 2.2.x(existing kork) to 2.3.x:
```> Task :echo-webhooks:compileGroovy
/echo/echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/config/WebhookProperties.java:21: error: package javax.validation does not exist
import javax.validation.Valid;
^
/echo/echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/config/WebhookProperties.java:22: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotEmpty;
^
/echo/echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/config/WebhookProperties.java:30: error: cannot find symbol
@Valid private List<WebhookArtifactTranslator> sources = new ArrayList<>();
^
symbol:   class Valid
location: class WebhookProperties …
```
> fix(echo-webhooks): add missing javax.validation:validation-api dependency.

- echo-notifications/src/main/resources/templates/manualJudgment/body-googlechat.ftl
- echo-notifications/src/main/resources/templates/manualJudgmentContinue/body-googlechat.ftl
- echo-notifications/src/main/resources/templates/manualJudgmentStop/body-googlechat.ftl
Copied the default template, but added some HTML tag to make the message more readable and also converted the additional instructions/messages with `markdownToHtml.convert(...)` since Google Chat support a [subset of HTML tags](https://developers.google.com/chat/reference/message-formats/cards#card_text_formatting).
fix https://github.com/spinnaker/spinnaker/issues/6236
> fix(templates/googlechat): custom template

- echo-model/src/main/java/com/netflix/spinnaker/echo/model/trigger/GitEvent.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/GitEventHandler.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/GithubWebhookEventHandler.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/github/GithubPullRequestEvent.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/github/GithubPushEvent.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/github/GithubWebhookEvent.java
- echo-webhooks/src/test/groovy/com/netflix/spinnaker/echo/controllers/WebhooksControllerSpec.groovy
Add PR number, draft status, state and title to the pull request event.
Also did some cleanup of the `GithubWebhookEvent` interface and removed unused parameters.
> feat(webhooks/github): Add more metadata to PR events

- Dockerfile.compile
This resolves a performance issue in JDK11 when Spinnaker is running in
a cluster with containerd.
> chore(dockerfile): upgrade to latest alpine image

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/artifacts/ArtifactMatcher.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/artifacts/ArtifactMatcherSpec.groovy
Currently, if a user accidentally configures a pipeline trigger with an invalid regex for a constraint value, echo throws a `PatternSyntaxException` any time it receives an event that should be tested against the constraint.  As a result, all pipeline triggers using the same trigger type & source/subscription will be non-functional, not just the pipeline with the bad regex.
This patch catches `PatternSyntaxException`, logs an error about the bad regex for troubleshooting purposes, and returns `false` such that the bad regex will never match, allowing all other pipeline triggers to continue functioning normally.
We haven't raised an issue for this as it's a fairly trivial bug & fix.
> fix(pipelineTriggers): handle invalid constraint regexes

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/EmailNotificationAgent.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/EmailNotificationAgentSpec.groovy
Application names can contain spaces. These spaces should be properly encoded in the url in email notifications
Before:
After:
> fix(notifications): Encode url in email notification

- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/BitbucketWebhookEventHandler.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/bitbucket/server/BitbucketServerEventHandler.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/bitbucket/server/BitbucketServerPrEvent.java
- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/bitbucket/server/BitbucketServerRepoEvent.java
- echo-webhooks/src/test/java/com/netflix/spinnaker/echo/scm/BitbucketWebhookEventHandlerTest.java
- echo-webhooks/src/test/java/com/netflix/spinnaker/echo/scm/bitbucket/server/BitbucketServerEventHandlerTest.java
- echo-webhooks/src/test/resources/bitbucket-server/bitbucket_server_pr_declined_payload.json
- echo-webhooks/src/test/resources/bitbucket-server/bitbucket_server_pr_deleted_payload.json
- echo-webhooks/src/test/resources/bitbucket-server/bitbucket_server_pr_from_ref_updated_payload.json
- echo-webhooks/src/test/resources/bitbucket-server/bitbucket_server_pr_merged_payload.json
- echo-webhooks/src/test/resources/bitbucket-server/bitbucket_server_pr_opened_payload.json
- echo-webhooks/src/test/resources/bitbucket-server/bitbucket_server_repo_refs_changed_payload.json
Backporting https://github.com/spinnaker/echo/pull/1219 under a feature flag.
* Separate Bitbucket Server logic into its own class.
* Move Bitbucket Server Event classes into its own classes.
Bitbucket Server events:
* pr:opened
* pr:from_ref_updated
* pr:deleted
* pr:declined
> feat(webhooks): Handle Bitbucket Server PR events (backport #1219)

- echo-web/echo-web.gradle
The properties spring.config.additional-location and spring.profiles.active are redundant in echo-web.gradle file. These properties are set by class com.netflix.spinnaker.kork.boot.DefaultPropertiesBuilder in com.netflix.spinnaker.echo.Application. So removing it from gradle file.
> refactor(web): Clean up redundant spring property in gradle file

- build.gradle
- echo-notifications/echo-notifications.gradle
with a specific goal to get `org.testng:testng:7.4.0` out of shipping code, since it's vulnerable to CVE-2022-4065.
> chore(dependencies): remove dependency on groovy-all

- echo-rest/src/main/java/com/netflix/spinnaker/echo/events/RestEventListener.java
- echo-rest/src/main/java/com/netflix/spinnaker/echo/events/RestEventService.java
- echo-rest/src/test/groovy/com/netflix/spinnaker/echo/events/RestEventListenerSpec.groovy
**Description**
The event may have payload size up to 10 MB and even more, there are no strict limits. The number of events to be sent can be large. It depends on how frequently Spinnaker runs pipelines, and other internal jobs. As a result, if consumer API is unavailable or has high latency then Echo service is constantly restarting due to Out of Memory error.
**How to use?**
Add to `echo-local.yml`:
```
rest:
enabled: true
circuitBreakerEnabled: true
resilience4j:
circuitbreaker:
instances:
sendEvent:
failure-rate-threshold: 50
minimum-number-of-calls: 5
automatic-transition-from-open-to-half-open-enabled: true
wait-duration-in-open-state: 5s
permitted-number-of-calls-in-half-open-state: 3
sliding-window-size: 10
sliding-window-type: count_based
```
> feat(event): Add circuit breaker for events sending.

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/PubsubEventHandler.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/PubsubEventHandlerSpec.groovy
It is nice how how Jenkins triggers display a link back to the build that triggered the pipeline. This keys off the link and linkText properties in the Trigger object. I would like to see this same behavior supported for pubsub triggers. This change allows senders of pubsub events to add link and linkText in the trigger message payload, and thus set a link that will be displayed in the pipeline execution UI.
I tested this out on our spinnaker installation and it renders the link like a champ:
> feat(pubsub): add support for links in pubsub triggers

- echo-rest/src/main/java/com/netflix/spinnaker/echo/events/RestEventListener.java
It should be optional - if no config is defined in the YAML file, it should disable the circuit breaker feature by default
> fix: The circuit breaker feature for sending events to telemetry endpoint is hidden under a required feature flag property

- echo-webhooks/src/main/groovy/com/netflix/spinnaker/echo/scm/BitbucketWebhookEventHandler.java
- echo-webhooks/src/test/groovy/com/netflix/spinnaker/echo/controllers/WebhooksControllerSpec.groovy
- echo-webhooks/src/test/java/com/netflix/spinnaker/echo/scm/BitbucketWebhookEventHandlerTest.java
Some Bitbucket Cloud webhooks do not have `repository.owner.username` field. This caused the `repoProject` event field to be empty and echo did not trigger pipelines correctly.
> fix(bitbucket): Add project key as identifier

- build.gradle
- echo-api-tck/echo-api-tck.gradle
- echo-api/echo-api.gradle
- echo-pipelinetriggers/echo-pipelinetriggers.gradle
- echo-plugins-test/echo-plugins-test.gradle
- echo-telemetry/echo-telemetry.gradle
- echo-web/src/test/java/com/netflix/spinnaker/echo/ApplicationSpec.java
- echo-web/src/test/java/com/netflix/spinnaker/echo/telemetry/TelemetrySpec.java
- echo-web/src/test/resources/echo-test.yml
- echo-webhooks/echo-webhooks.gradle
Spring boot 2.4.x removed JUnit5 vintage engine from spring-boot-starter-test. 
[https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#junit-5s-vintage-engine-removed-from-spring-boot-starter-test] It is required for executing junit4 based test cases in echo. So, introducing junit-vintage-engine dependency in build.gradle, using testRuntimeOnly() as suggested in section 3.1 of https://junit.org/junit5/docs/5.6.2/user-guide/index.pdf
After applying this fix, coverage increased from 533 to 535 test case executions.
Clean up the call for test engines using `useJUnitPlatform()` from sub-modules, and placing it in build.gradle. As per the gradle docs, all test engines on the test runtime classpath will be used by sub modules. …
> fix(tests): Introduce junit5 vintage engine for running junit4 test cases over junit5 and cleanup of useJUnitPlatform() from sub-modules in echo

- echo-core/src/main/java/com/netflix/spinnaker/echo/services/Front50Service.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/PipelineTriggerConfiguration.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCache.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCacheConfigurationProperties.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ManualEventHandler.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCacheSpec.groovy
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/ManualEventHandlerSpec.groovy
- echo-pipelinetriggers/src/test/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCacheTest.java
when pipelineCache.filterFront50Pipelines is true.  Determine the specific types from the types that the available BaseTriggerEventHandler beans support, with cron triggers as well. Adjust the logic in ManualEventHandler to work when the cache only contains a subset of pipelines.
When pipelineCache.filterFront50Pipelines is false, retain the current behavior to query front50 for all pipelines.
Note that both before and after this change, when ManualEventHandler gets a pipeline from the cache, it queries front50 for a single pipeline by id to make sure what it's triggering is up to date.  As currently implemented, front50 queries its database by id to generate the response.
Currently, deck triggers by pipeline application + name.  See for example …
> feat(pipelinetriggers): only cache enabled pipelines with enabled triggers of specific types

- echo-api-tck/echo-api-tck.gradle
- echo-pipelinetriggers/echo-pipelinetriggers.gradle
- echo-plugins-test/echo-plugins-test.gradle
- echo-telemetry/src/test/kotlin/com/netflix/spinnaker/echo/telemetry/ExecutionDataProviderTest.kt
- echo-webhooks/echo-webhooks.gradle
Before refactor, total test cases executed were 553, 6 ignored. 
After refactor, total test cases executed are 553, 6 ignored.
> refactor(tests): convert junit4 based testcases to junit5 and clean up in echo

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/GithubConfig.java
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/config/GithubConfigSpec.groovy
Fixes output logs when using github status checks
> fix(gha): Fix github status log and add tests

- echo-core/echo-core.gradle
- echo-pipelinetriggers/echo-pipelinetriggers.gradle
While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, groovy-json is not part of [spockframework](https://mvnrepository.com/artifact/org.spockframework/spock-core/2.0-groovy-3.0) and encounter below error during test compilation:
```
> Task :echo-core:compileTestGroovy
startup failed:
/echo/echo-core/src/test/groovy/com/netflix/spinnaker/echo/services/Front50ServiceSpec.groovy: 3: unable to resolve class groovy.json.JsonOutput
@ line 3, column 1.
import groovy.json.JsonOutput
^
1 error
> Task :echo-core:compileTestGroovy FAILED
```
```
> Task :echo-pipelinetriggers:compileTestGroovy
startup failed:
/echo/echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/CDEventsWebhookHandlerSpec.groovy: 28: unable to resolve class …
```
> chore(dependency): add explicit dependency of groovy-json in echo-core and echo-pipelinetriggers while upgrading groovy 3.x

- echo-core/src/test/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgentSpec.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/GithubNotificationAgentSpec.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/GoogleChatNotificationAgentSpec.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/SlackNotificationAgentSpec.groovy
While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encountered the following errors in groovy test compilation of echo-core and echo-notifications modules:
```
startup failed:
/echo/echo-core/src/test/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgentSpec.groovy: 42: The current scope already contains a variable of the name event
@ line 42, column 43.
Mock.sendNotifications(*_) >> { notifica
^
1 error
> Task :echo-core:compileTestGroovy FAILED
```
```
startup failed:
/echo/echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/GithubNotificationAgentSpec.groovy: 50: The current scope already contains a variable of the name status
@ line 50, column 31.
github.updateCheck(*_) >> { token, repo, sha, status ->
^
1 error
> Task …
```
> refactor(tests): fix conflict of variable scope by renaming local variables during upgrade of groovy 3.x

- echo-core/src/main/java/com/netflix/spinnaker/echo/build/BuildInfoService.java
- echo-core/src/main/java/com/netflix/spinnaker/echo/services/IgorService.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BuildEventHandlerSpec.groovy
Fixes https://github.com/spinnaker/spinnaker/issues/6928
The implementation of: 
```
feature:
igor:
jobNameAsQueryParameter: true
```
did not include the support  for Jenkins artifacts and property files leading to failures on Manual triggers and rerun's of a Spinnaker pipeline retrieving BuildInfo from the sub-folder Jenkins job.
> fix(jenkins): Enable properties and artifacts with job name as query parameter

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/config/PipelineTriggerConfiguration.java
- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ExpectedArtifactExpressionEvaluationPostProcessor.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ExpectedArtifactExpressionEvaluationPostProcessorSpec.groovy
- echo-pipelinetriggers/src/test/java/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ExpectedArtifactExpressionLengthTest.java
Spring Expression Lanuage (SpEL) has a default limit of 10,000 characters. Springframework provides the feature to configure the limit. This feature allows to configure the limit of characters for SpEL expressions.
Approach:
In order to use an expression with characters more than the given default limit, require to follow either of the below approaches:
1. For Springframework >=5.3.28 and <6.1.3, by setting `maximumExpressionLength` field while instantiating the custom `SpelParserConfiguration` class. 
https://github.com/spring-projects/spring-framework/issues/30380 
https://github.com/spring-projects/spring-framework/issues/30446
3. For Springframework >=6.1.3, by setting a JVM system property or Spring property named `spring.context.expression.maxLength` to the maximum expression length …
> feat(SpEL): implement to configure the limit of characters for SpEL expressions

- build.gradle
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ExpectedArtifactExpressionEvaluationPostProcessorSpec.groovy
that uses a non-public constructor/method, and so requires special treatment under java 17.
> test(pipelinetriggers): demonstrate behavior of SpEL expression evaluation

- echo-notifications/echo-notifications.gradle
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/cdevents/CDEventPipelineRunFinished.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/cdevents/CDEventPipelineRunQueued.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/cdevents/CDEventPipelineRunStarted.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/cdevents/CDEventTaskRunFinished.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/cdevents/CDEventTaskRunStarted.java
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/cdevents/CDEventsBuilderService.java
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/CDEventsNotificationAgentSpec.groovy
- gradle.properties
* Added support for CDEvents customData so that pipelines can add additional custom data to the event notification.
> feat(notifications/cdEvents): added support for customData

- echo-test/src/main/groovy/com/netflix/spinnaker/echo/test/RetrofitStubs.groovy
While upgrading groovy to 4.0.15, encountered the errors in echo-test module, similar to following error is appearing for multiple tests:
```
Failed to instantiate spec 'PipelineCacheSpec'
org.spockframework.util.InternalSpockError: Failed to instantiate spec 'PipelineCacheSpec'
at app//org.spockframework.runtime.PlatformSpecRunner.createSpecInstance(PlatformSpecRunner.java:80)
at app//org.spockframework.runtime.PlatformSpecRunner.runSharedSpec(PlatformSpecRunner.java:45)
at app//org.spockframework.runtime.SpecNode.prepare(SpecNode.java:32)
at app//org.spockframework.runtime.SpecNode.prepare(SpecNode.java:11)
at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.e …
```
> refactor(test): fix test failure due to NullPointerException during upgrade of groovy 4.x

- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/config/JiraConfig.java
- echo-scheduler/src/main/groovy/com/netflix/spinnaker/echo/config/SchedulerConfiguration.groovy
- echo-telemetry/echo-telemetry.gradle
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/config/TelemetryConfig.kt
Moving away from `com.squareup.okhttp.OkHttpClient` to `okhttp3.OkHttpClient` to avoid any unwanted dependency conflicts.
okhttp3.OkHttpClient for retrofit1 is provided by [Ok3Client](https://github.com/JakeWharton/retrofit1-okhttp3-client)
> refactor(retrofit): replace OkClient with Ok3Client

- echo-rest/echo-rest.gradle
- echo-rest/src/main/java/com/netflix/spinnaker/echo/events/RestEventService.java
- echo-rest/src/test/java/com/netflix/spinnaker/echo/events/RestEventListenerTest.java
- echo-rest/src/test/java/com/netflix/spinnaker/echo/events/RestEventServiceTest.java
- added a test to demonstrate that RestEventService.sendEvent is failing to make the RestService.recordEvent api call
- fixed the issue and updated the test accordingly
> fix(rest): add Retrofit2SyncCall.execute to RestService in RestEventService

- echo-notifications/echo-notifications.gradle
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/bearychat/BearychatNotificationService.groovy
- echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/bearychat/BearychatService.groovy
- echo-notifications/src/test/java/com/netflix/spinnaker/echo/bearychat/BearychatNotificationServiceTest.java
- Add a test to demonstrate the missing Retrofit2SyncCall.execute calls in BearychatNotificationService
- add Retrofit2SyncCall.execute to BearychatService in BearychatNotificationService
> fix(notifications): add Retrofit2SyncCall.execute to BearychatService in BearychatNotificationService

- echo-notifications/src/main/java/com/netflix/spinnaker/echo/config/MicrosoftTeamsConfig.java
- echo-notifications/src/test/java/com/netflix/spinnaker/echo/config/MicrosoftTeamsServiceTest.java
- fixed MicrosoftTeamsConfig
- added a test to verify that MicrosoftTeamsService gets created now
> fix(notifications): fix MicrosoftTeamsConfig which has unused retrofit1 parameters

- echo-core/src/main/java/com/netflix/spinnaker/echo/services/IgorService.java
- echo-core/src/test/java/com/netflix/spinnaker/echo/services/IgorServiceTest.java
- echo-core/src/test/resources/logback-test.xml
- echo-notifications/src/main/java/com/netflix/spinnaker/echo/notification/GoogleCloudBuildNotificationAgent.java
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/GoogleCloudBuildNotificationSpec.groovy
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/slack/SlackServiceSpec.groovy
- echo-pubsub-google/src/main/java/com/netflix/spinnaker/echo/pubsub/google/GoogleCloudBuildArtifactExtractor.java
- echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/TelemetryEventListener.java
- Added a test to demonstrate the issue of remnants of retrofit1 still being present while retrofit2 client is used. 
- Fixed the issue by replacing the retrofit1 objects with appropriate retrofit2 counter parts.
> fix(retrofit): address remnants of retrofit1 like TypedInput, TypedByteArray etc

- echo-notifications/echo-notifications.gradle
- echo-notifications/src/main/java/com/netflix/spinnaker/echo/notification/GoogleCloudBuildNotificationAgent.java
- echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/notification/GoogleCloudBuildNotificationSpec.groovy
- echo-notifications/src/test/java/com/netflix/spinnaker/echo/notification/GoogleCloudBuildNotificationAgentTest.java
- Add a test to demonstrate the issue of missing Retrofit2SyncCall.execute call in GoogleCloudBuildNotificationAgent
- Fix the issue and update the tests accordingly
> fix(retrofit2): fix google cloud build notification agent for missing Retrofit2SyncCall.execute call

- echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCacheConfigurationProperties.java
- echo-pipelinetriggers/src/test/groovy/com/netflix/spinnaker/echo/pipelinetriggers/PipelineCacheSpec.groovy
until bugs are fixed.
For reference, https://github.com/spinnaker/echo/pull/1416 enabled pipeline filtering by default.
> fix(pipelinetriggers): turn off pipeline filtering by default

- echo-core/src/main/java/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.java
- echo-core/src/test/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgentSpec.groovy
this is fix for https://github.com/spinnaker/spinnaker/issues/7051
> fix(notifications): Prevent duplicate notifications for MJ 
